# SPDX-License-Identifier: GPL-2.0-or-later
#
# bash tab completion for the nvme command line utility
#
# This file is generated by generate-completions.py. Do not edit.

# Helper function to detect if we're completing an option's value.
# Uses: $cur, $prev, $words, $cword (from _init_completion)
# Sets: $opt (the option name), $val (partial value), $completing_value (0 or 1)
_nvme_detect_value_completion() {
	completing_value=0
	opt=""
	val=""

	if [[ $cur == --*= ]]; then
		opt="${cur%=}"
		completing_value=1
	elif [[ $cur == "=" ]] && [[ $prev == --* ]]; then
		opt="$prev"
		completing_value=1
	elif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == "=" ]] && [[ ${words[$cword-2]} == --* ]]; then
		opt="${words[$cword-2]}"
		val="$cur"
		completing_value=1
	elif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == --* ]]; then
		opt="$prev"
		val="$cur"
		completing_value=1
	elif [[ $cur == "" ]] && [[ $prev == --* ]]; then
		opt="$prev"
		completing_value=1
	elif [[ $cur == "" ]] && [[ $prev == "=" ]]; then
		opt="${words[$cword-2]}"
		completing_value=1
	elif [[ $cur == "" ]] && [[ $prev == -? ]]; then
		opt="$prev"
		completing_value=1
	elif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == -? ]]; then
		opt="$prev"
		val="$cur"
		completing_value=1
	fi
}

nvme_list_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 2 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help"|"gen-hostnqn"|"show-hostnqn"|"dump-command-metadata")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"list")
		opts+=""
			;;
		"list-subsys")
		opts+=""
			;;
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
		"id-ns")
		opts+=" --namespace-id= -n --force --vendor-specific -V --raw-binary -b"
			;;
		"id-ns-granularity")
		opts+=""
			;;
		"id-ns-lba-format")
		opts+=" --lba-format-index= -i --uuid-index= -U"
			;;
		"list-ns")
		opts+=" --namespace-id= -n --csi= -y --all -a"
			;;
		"list-ctrl")
		opts+=" --cntid= -c --namespace-id= -n"
			;;
		"nvm-id-ctrl")
		opts+=""
			;;
		"nvm-id-ns")
		opts+=" --namespace-id= -n --uuid-index= -U"
			;;
		"nvm-id-ns-lba-format")
		opts+=" --lba-format-index= -i --uuid-index= -U"
			;;
		"primary-ctrl-caps")
		opts+=" --cntlid= -c"
			;;
		"list-secondary")
		opts+=" --cntid= -c --num-entries= -e"
			;;
		"cmdset-ind-id-ns")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"ns-descs")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"id-nvmset")
		opts+=" --nvmset_id= -i"
			;;
		"id-uuid")
		opts+=" --raw-binary -b"
			;;
		"id-iocs")
		opts+=" --controller-id= -c"
			;;
		"id-domain")
		opts+=" --dom-id= -d"
			;;
		"list-endgrp")
		opts+=" --endgrp-id= -i"
			;;
		"create-ns")
		opts+=" --ish -I --nsze= -s --ncap= -c --flbas= -f --dps= -d --nmic= -m --anagrp-id= -a --nvmset-id= -i --endg-id= -e --block-size= -b --csi= -y --lbstm= -l --nphndls= -n --nsze-si= -S --ncap-si= -C --azr -z --rar= -r --ror= -O --rnumzrwa= -u --phndls= -p"
			;;
		"delete-ns")
		opts+=" --ish -I --namespace-id= -n"
			;;
		"attach-ns")
		opts+=" --ish -I --namespace-id= -n --controllers= -c"
			;;
		"detach-ns")
		opts+=" --ish -I --namespace-id= -n --controllers= -c"
			;;
		"get-ns-id")
		opts+=""
			;;
		"get-log")
		opts+=" --ish -I --namespace-id= -n --log-id= -i --log-len= -l --aen= -a --lpo= -L --lsp= -s --lsi= -S --rae -r --uuid-index= -U --raw-binary -b --csi= -y --ot -O --xfer-len= -x"
			;;
		"telemetry-log")
		opts+=" --output-file= -O --host-generate= -g --controller-init -c --data-area= -d --rae -r --mcda= -m"
			;;
		"fw-log")
		opts+=" --raw-binary -b"
			;;
		"changed-ns-list-log")
		opts+=" --raw-binary -b"
			;;
		"smart-log")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"ana-log")
		opts+=" --groups -g"
			;;
		"error-log")
		opts+=" --log-entries= -e --raw-binary -b --valid-entry -V --sqid= -S --status= -s --lba= -l --namespace-id= -n --trtype= -t --csi= -c --opcode= -O"
			;;
		"effects-log")
		opts+=" --raw-binary -b --csi= -c"
			;;
		"endurance-log")
		opts+=" --group-id= -g"
			;;
		"predictable-lat-log")
		opts+=" --nvmset-id= -i --raw-binary -b"
			;;
		"pred-lat-event-agg-log")
		opts+=" --log-entries= -e --rae -r --raw-binary -b"
			;;
		"persistent-event-log")
		opts+=" --action= -a --log_len= -l --raw-binary -b"
			;;
		"endurance-event-agg-log")
		opts+=" --log-entries= -e --rae -r --raw-binary -b"
			;;
		"lba-status-log")
		opts+=" --rae -r"
			;;
		"resv-notif-log")
		opts+=""
			;;
		"boot-part-log")
		opts+=" --lsp= -s --output-file= -f"
			;;
		"phy-rx-eom-log")
		opts+=" --lsp= -s --controller= -c"
			;;
		"get-feature")
		opts+=" --feature-id= -f --namespace-id= -n --sel= -s --data-len= -l --raw-binary -b --cdw11= -c --uuid-index= -U --changed -C"
			;;
		"device-self-test")
		opts+=" --ish -I --namespace-id= -n --self-test-code= -s --wait -w"
			;;
		"self-test-log")
		opts+=" --dst-entries= -e"
			;;
		"supported-log-pages")
		opts+=""
			;;
		"fid-support-effects-log")
		opts+=""
			;;
		"mi-cmd-support-effects-log")
		opts+=""
			;;
		"media-unit-stat-log")
		opts+=" --domain-id= -d --raw-binary -b"
			;;
		"supported-cap-config-log")
		opts+=" --domain-id= -d --raw-binary -b"
			;;
		"mgmt-addr-list-log")
		opts+=""
			;;
		"rotational-media-info-log")
		opts+=" --endg-id= -e"
			;;
		"changed-alloc-ns-list-log")
		opts+=" --raw-binary -b"
			;;
		"dispersed-ns-participating-nss-log")
		opts+=" --namespace-id= -n"
			;;
		"reachability-groups-log")
		opts+=" --groups-only -g --rae -r"
			;;
		"reachability-associations-log")
		opts+=" --associations-only -a --rae -r"
			;;
		"host-discovery-log")
		opts+=" --all-host-entries -a --rae -r"
			;;
		"ave-discovery-log")
		opts+=" --rae -r"
			;;
		"pull-model-ddc-req-log")
		opts+=" --rae -r"
			;;
		"power-measurement-log")
		opts+=" --raw-binary -b"
			;;
		"set-feature")
		opts+=" --namespace-id= -n --feature-id= -f --value= -V --cdw12= -c --uuid-index= -U --data-len= -l --data= -d --save -s"
			;;
		"set-property")
		opts+=" --offset= -O --value= -V"
			;;
		"get-property")
		opts+=" --offset= -O"
			;;
		"format")
		opts+=" --ish -I --namespace-id= -n --lbaf= -l --ses= -s --pi= -i --pil= -p --ms= -m --reset -r --force --block-size= -b"
			;;
		"fw-commit")
		opts+=" --ish -I --slot= -s --action= -a --bpid= -b"
			;;
		"fw-download")
		opts+=" --fw= -f --ish -I --xfer= -x --offset= -O --progress -p --ignore-ovr -i"
			;;
		"admin-passthru")
		opts+=" --opcode= -O --flags= -f --prefill= -p --rsvd= -R --namespace-id= -n --data-len= -l --metadata-len= -m --cdw2= -2 --cdw3= -3 --cdw10= -4 --cdw11= -5 --cdw12= -6 --cdw13= -7 --cdw14= -8 --cdw15= -9 --input-file= -i --metadata= -M --raw-binary -b --show-command -s --read -r --write -w --latency -T"
			;;
		"io-passthru")
		opts+=" --opcode= -O --flags= -f --prefill= -p --rsvd= -R --namespace-id= -n --data-len= -l --metadata-len= -m --cdw2= -2 --cdw3= -3 --cdw10= -4 --cdw11= -5 --cdw12= -6 --cdw13= -7 --cdw14= -8 --cdw15= -9 --input-file= -i --metadata= -M --raw-binary -b --show-command -s --read -r --write -w --latency -T"
			;;
		"security-send")
		opts+=" --ish -I --namespace-id= -n --file= -f --nssf= -N --secp= -p --spsp= -s --tl= -t"
			;;
		"security-recv")
		opts+=" --ish -I --namespace-id= -n --size= -x --nssf= -N --secp= -p --spsp= -s --al= -t --raw-binary -b"
			;;
		"get-lba-status")
		opts+=" --ish -I --namespace-id= -n --start-lba= -s --max-dw= -m --action= -a --range-len= -l"
			;;
		"capacity-mgmt")
		opts+=" --ish -I --operation= -O --element-id= -i --cap-lower= -l --cap-upper= -u"
			;;
		"resv-acquire")
		opts+=" --namespace-id= -n --crkey= -c --prkey= -p --rtype= -t --racqa= -a --iekey -i"
			;;
		"resv-register")
		opts+=" --namespace-id= -n --crkey= -c --nrkey= -k --rrega= -r --cptpl= -p --iekey -i"
			;;
		"resv-release")
		opts+=" --namespace-id= -n --crkey= -c --rtype= -t --rrela= -a --iekey -i"
			;;
		"resv-report")
		opts+=" --namespace-id= -n --numd= -d --eds -e --raw-binary -b"
			;;
		"dsm")
		opts+=" --namespace-id= -n --ctx-attrs= -a --blocks= -b --slbs= -s --ad -d --idw -w --idr -r --cdw11= -c"
			;;
		"copy")
		opts+=" --namespace-id= -n --sdlba= -d --slbs= -s --blocks= -b --snsids= -N --sopts= -O --limited-retry -l --force-unit-access -f --prinfow= -p --prinfor= -P --ref-tag= -r --expected-ref-tags= -R --app-tag= -a --expected-app-tags= -A --app-tag-mask= -m --expected-app-tag-masks= -M --dir-type= -T --dir-spec= -S --format= -F --storage-tag= -t --storage-tag-check -c"
			;;
		"flush")
		opts+=" --namespace-id= -n"
			;;
		"compare")
		opts+=" --namespace-id= -n --start-block= -s --block-count= -c --block-size= -b --data-size= -z --metadata-size= -y --ref-tag= -r --data= -d --metadata= -M --prinfo= -p --app-tag-mask= -m --app-tag= -a --storage-tag= -g --limited-retry -l --force-unit-access -f --storage-tag-check -C --dir-type= -T --dir-spec= -S --dsm= -D --show-command -V --latency -t --force"
			;;
		"read")
		opts+=" --namespace-id= -n --start-block= -s --block-count= -c --block-size= -b --data-size= -z --metadata-size= -y --ref-tag= -r --data= -d --metadata= -M --prinfo= -p --app-tag-mask= -m --app-tag= -a --storage-tag= -g --limited-retry -l --force-unit-access -f --storage-tag-check -C --dir-type= -T --dir-spec= -S --dsm= -D --show-command -V --latency -t --force"
			;;
		"write")
		opts+=" --namespace-id= -n --start-block= -s --block-count= -c --block-size= -b --data-size= -z --metadata-size= -y --ref-tag= -r --data= -d --metadata= -M --prinfo= -p --app-tag-mask= -m --app-tag= -a --storage-tag= -g --limited-retry -l --force-unit-access -f --storage-tag-check -C --dir-type= -T --dir-spec= -S --dsm= -D --show-command -V --latency -t --force"
			;;
		"write-zeroes")
		opts+=" --namespace-id= -n --start-block= -s --block-count= -c --dir-type= -T --deac -d --limited-retry -l --force-unit-access -f --prinfo= -p --ref-tag= -r --app-tag-mask= -m --app-tag= -a --storage-tag= -S --storage-tag-check -C --dir-spec= -D --namespace-zeroes -Z"
			;;
		"write-uncor")
		opts+=" --namespace-id= -n --start-block= -s --block-count= -c --dir-type= -T --dir-spec= -S"
			;;
		"verify")
		opts+=" --namespace-id= -n --start-block= -s --block-count= -c --limited-retry -l --force-unit-access -f --prinfo= -p --ref-tag= -r --app-tag= -a --app-tag-mask= -m --storage-tag= -S --storage-tag-check -C"
			;;
		"sanitize")
		opts+=" --ish -I --no-dealloc -d --oipbp -i --owpass= -n --ause -u --sanact= -a --ovrpat= -p --emvs -e --wait -w --repeat= -r"
			;;
		"sanitize-log")
		opts+=" --rae -r --raw-binary -b"
			;;
		"sanitize-ns")
		opts+=" --ish -I --ause -u --sanact= -a --emvs -e"
			;;
		"reset")
		opts+=""
			;;
		"subsystem-reset")
		opts+=""
			;;
		"ns-rescan")
		opts+=""
			;;
		"show-regs")
		opts+=""
			;;
		"set-reg")
		opts+=" --offset= -O --value= -V --mmio32 -m --intms= --intmc= --cc= --csts= --nssr= --aqa= --asq= --acq= --bprsel= --bpmbl= --cmbmsc= --nssd= --pmrctl= --pmrmscl= --pmrmscu="
			;;
		"get-reg")
		opts+=" --offset= -O --cap --vs --cmbloc --cmbsz --bpinfo --cmbsts --cmbebs --cmbswtp --crto --pmrcap --pmrsts --pmrebs --pmrswtp --intms --intmc --cc --csts --nssr --aqa --asq --acq --bprsel --bpmbl --cmbmsc --nssd --pmrctl --pmrmscl --pmrmscu"
			;;
		"top")
		opts+=" --delay= -d"
			;;
		"discover")
		opts+=" --transport= -t --nqn= -n --traddr= -a --trsvcid= -s --host-traddr= -w --host-iface= -f --hostnqn= -q --hostid= -I --dhchap-secret= -S --dhchap-ctrl-secret= -C --keyring= --tls-key= --tls-key-identity= --nr-io-queues= -i --nr-write-queues= -W --nr-poll-queues= -P --queue-size= -Q --keep-alive-tmo= -k --reconnect-delay= -c --ctrl-loss-tmo= -l --fast_io_fail_tmo= -F --tos= -T --tls_key= --duplicate-connect -D --disable-sqflow --hdr-digest -g --data-digest -G --tls --concat --device= -d --raw= -r --persistent -p --quiet --config= -J --dump-config -O --force --nbft --no-nbft --owner= --nbft-path="
			;;
		"connect-all")
		opts+=" --transport= -t --nqn= -n --traddr= -a --trsvcid= -s --host-traddr= -w --host-iface= -f --hostnqn= -q --hostid= -I --dhchap-secret= -S --dhchap-ctrl-secret= -C --keyring= --tls-key= --tls-key-identity= --nr-io-queues= -i --nr-write-queues= -W --nr-poll-queues= -P --queue-size= -Q --keep-alive-tmo= -k --reconnect-delay= -c --ctrl-loss-tmo= -l --fast_io_fail_tmo= -F --tos= -T --tls_key= --duplicate-connect -D --disable-sqflow --hdr-digest -g --data-digest -G --tls --concat --device= -d --raw= -r --persistent -p --quiet --config= -J --dump-config -O --force --nbft --no-nbft --owner= --nbft-path="
			;;
		"connect")
		opts+=" --transport= -t --nqn= -n --traddr= -a --trsvcid= -s --host-traddr= -w --host-iface= -f --hostnqn= -q --hostid= -I --dhchap-secret= -S --dhchap-ctrl-secret= -C --keyring= --tls-key= --tls-key-identity= --nr-io-queues= -i --nr-write-queues= -W --nr-poll-queues= -P --queue-size= -Q --keep-alive-tmo= -k --reconnect-delay= -c --ctrl-loss-tmo= -l --fast_io_fail_tmo= -F --tos= -T --tls_key= --duplicate-connect -D --disable-sqflow --hdr-digest -g --data-digest -G --tls --concat --config= -J --owner= --dump-config -O"
			;;
		"disconnect")
		opts+=" --nqn= -n --device= -d"
			;;
		"disconnect-all")
		opts+=" --transport= -t --owner= --force"
			;;
		"config")
		opts+=" --transport= -t --nqn= -n --traddr= -a --trsvcid= -s --host-traddr= -w --host-iface= -f --hostnqn= -q --hostid= -I --dhchap-secret= -S --dhchap-ctrl-secret= -C --keyring= --tls-key= --tls-key-identity= --nr-io-queues= -i --nr-write-queues= -W --nr-poll-queues= -P --queue-size= -Q --keep-alive-tmo= -k --reconnect-delay= -c --ctrl-loss-tmo= -l --fast_io_fail_tmo= -F --tos= -T --tls_key= --duplicate-connect -D --disable-sqflow --hdr-digest -g --data-digest -G --tls --concat --config= -J --scan -R --modify -M --dump -O --update -U"
			;;
		"dim")
		opts+=" --nqn= -n --device= -d --task= -t"
			;;
		"gen-dhchap-key")
		opts+=" --secret= -s --key-length= -l --nqn= -n --hmac= -m"
			;;
		"check-dhchap-key")
		opts+=" --key= -k"
			;;
		"gen-tls-key")
		opts+=" --keyring= -k --keytype= -t --hostnqn= -n --subsysnqn= -c --secret= -s --keyfile= -f --hmac= -m --identity= -I --insert -i --compat -C"
			;;
		"check-tls-key")
		opts+=" --keyring= -k --keytype= -t --hostnqn= -n --subsysnqn= -c --keydata= -d --keyfile= -f --identity= -I --insert -i --compat -C"
			;;
		"tls-key")
		opts+=" --keyring= -k --keytype= -t --keyfile= -f --import -i --export -e --revoke= -r"
			;;
		"dir-receive")
		opts+=" --namespace-id= -n --data-len= -l --raw-binary -b --dir-type= -D --dir-spec= -S --dir-oper= -O --req-resource= -r"
			;;
		"dir-send")
		opts+=" --namespace-id= -n --data-len= -l --dir-type= -D --target-dir= -T --dir-spec= -S --dir-oper= -O --endir= -e --raw-binary -b --input-file= -i"
			;;
		"virt-mgmt")
		opts+=" --cntlid= -c --rt= -r --act= -a --nr= -n"
			;;
		"rpmb")
		opts+=" --cmd= -c --msgfile= -f --keyfile= -g --key= -k --msg= -d --address= -o --blocks= -b --target= -t"
			;;
		"lockdown")
		opts+=" --ofi= -O --ifc= -f --prhbt= -p --scp= -s --uuid= -U"
			;;
		"show-topology")
		opts+=" --ranking= -r"
			;;
		"io-mgmt-recv")
		opts+=" --namespace-id= -n --mos= -s --mo= -m --data= -d --data-len= -l"
			;;
		"io-mgmt-send")
		opts+=" --namespace-id= -n --mos= -s --mo= -m --data= -d --data-len= -l"
			;;
		"nvme-mi-recv")
		opts+=" --opcode= -O --namespace-id= -n --data-len= -l --nmimt= -m --nmd0= -0 --nmd1= -1 --input-file= -i"
			;;
		"nvme-mi-send")
		opts+=" --opcode= -O --namespace-id= -n --data-len= -l --nmimt= -m --nmd0= -0 --nmd1= -1 --input-file= -i"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_amzn_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
		"stats")
		opts+=" --details -d --interval= -i"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_dapustor_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b --json -j"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_dell_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_dera_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_fdp_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"configs")
		opts+=" --endgrp-id= -e --raw-binary -b --human-readable -H"
			;;
		"usage")
		opts+=" --endgrp-id= -e --raw-binary -b"
			;;
		"stats")
		opts+=" --endgrp-id= -e --raw-binary -b"
			;;
		"events")
		opts+=" --endgrp-id= -e --host-events -E --raw-binary -b"
			;;
		"status")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"update")
		opts+=" --namespace-id= -n --pids= -p"
			;;
		"set-events")
		opts+=" --namespace-id= -n --placement-handle= -p --enable -e --save -s --event-types= -t"
			;;
		"feature")
		opts+=" --endgrp-id= -e --enable-conf-idx= -c --disable -d"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_huawei_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"list")
		opts+=""
			;;
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_ibm_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"crit-log")
		opts+=" --raw-binary -b"
			;;
		"vpd")
		opts+=" --raw-binary -b"
			;;
		"persist-event-log")
		opts+=" --action= -a --log_len= -l --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_innogrit_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"get-eventlog")
		opts+=""
			;;
		"get-cdump")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_inspur_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"nvme-vendor-log")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_intel_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
		"internal-log")
		opts+=" --log= -l --region= -r --nlognum= -m --namespace-id= -n --output-file= -O --verbose-nlog -V"
			;;
		"lat-stats")
		opts+=" --write -w --raw-binary -b --json -j"
			;;
		"set-bucket-thresholds")
		opts+=" --write -w --bucket-thresholds= -t"
			;;
		"lat-stats-tracking")
		opts+=" --enable -e --disable -d"
			;;
		"market-name")
		opts+=" --raw-binary -b"
			;;
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b --json -j"
			;;
		"temp-stats")
		opts+=" --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_mangoboost_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_memblaze_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"get-pm-status")
		opts+=""
			;;
		"set-pm-status")
		opts+=" --value= -V --save -s"
			;;
		"select-download")
		opts+=" --fw= -f --select= -s"
			;;
		"lat-stats")
		opts+=" --enable -e --disable -d"
			;;
		"lat-stats-print")
		opts+=" --write -w"
			;;
		"lat-log")
		opts+=" --param= -p"
			;;
		"lat-log-print")
		opts+=""
			;;
		"clear-error-log")
		opts+=""
			;;
		"smart-log-add-x")
		opts+=" --raw-binary -b"
			;;
		"lat-set-feature-x")
		opts+=" --sel-perf-log= -s --set-commands-mask= -m --set-read-threshold= -r --set-write-threshold= -w --set-trim-threshold= -t"
			;;
		"lat-get-feature-x")
		opts+=""
			;;
		"lat-stats-print-x")
		opts+=" --raw-binary -b"
			;;
		"lat-log-print-x")
		opts+=" --raw-binary -b"
			;;
		"perf-stats-print-x")
		opts+=" --duration= -d --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_micron_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help"|"plugin-version"|"cloud-SSD-plugin-version")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"select-download")
		opts+=" --fw= -f --select= -s"
			;;
		"vs-temperature-stats")
		opts+=" --format= -f"
			;;
		"vs-pcie-stats")
		opts+=" --format= -f"
			;;
		"clear-pcie-correctable-errors")
		opts+=""
			;;
		"vs-internal-log")
		opts+=" --type= -t --package= -p --data_area= -d"
			;;
		"vs-telemetry-controller-option")
		opts+=" --option= -O --select= -s"
			;;
		"vs-nand-stats")
		opts+=" --format= -f"
			;;
		"vs-smart-ext-log")
		opts+=" --format= -f"
			;;
		"vs-drive-info")
		opts+=" --format= -f"
			;;
		"log-page-directory")
		opts+=""
			;;
		"vs-fw-activate-history")
		opts+=" --format= -f"
			;;
		"latency-tracking")
		opts+=" --option= -O --command= -c --threshold= -t"
			;;
		"latency-stats")
		opts+=" --command= -c"
			;;
		"latency-logs")
		opts+=""
			;;
		"vs-smart-add-log")
		opts+=" --format= -f"
			;;
		"clear-fw-activate-history")
		opts+=""
			;;
		"vs-smbus-option")
		opts+=" --option= -O --value= -V --save= -s"
			;;
		"cloud-boot-SSD-version")
		opts+=" --format= -f"
			;;
		"vs-device-waf")
		opts+=" --format= -f"
			;;
		"vs-cloud-log")
		opts+=" --format= -f"
			;;
		"vs-work-load-log")
		opts+=" --format= -f"
			;;
		"vs-vendor-telemetry-log")
		opts+=" --format= -f"
			;;
		"smart-log")
		opts+=" --format= -f"
			;;
		"id-ctrl")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_netapp_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smdevices")
		opts+=""
			;;
		"ontapdevices")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_nvidia_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_sndk_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"vs-internal-log")
		opts+=" --output-file= -O --transfer-size= -s --data-area= -d --type= -t --verbose -V --file-size= -f --offset= -e"
			;;
		"vs-nand-stats")
		opts+=""
			;;
		"vs-smart-add-log")
		opts+=" --interval= -i --log-page-version= -l --log-page-mask= -p --namespace-id= -n"
			;;
		"clear-pcie-correctable-errors")
		opts+=""
			;;
		"get-drive-status")
		opts+=""
			;;
		"clear-assert-dump")
		opts+=""
			;;
		"drive-resize")
		opts+=" --size= -s"
			;;
		"vs-fw-activate-history")
		opts+=""
			;;
		"clear-fw-activate-history")
		opts+=""
			;;
		"vs-telemetry-controller-option")
		opts+=" --disable -d --enable -e --status -s"
			;;
		"vs-error-reason-identifier")
		opts+=" --log-id= -i --file= -O"
			;;
		"log-page-directory")
		opts+=""
			;;
		"namespace-resize")
		opts+=" --namespace-id= -n --op-option= -O"
			;;
		"vs-drive-info")
		opts+=""
			;;
		"vs-temperature-stats")
		opts+=""
			;;
		"capabilities")
		opts+=""
			;;
		"cloud-SSD-plugin-version")
		opts+=""
			;;
		"vs-pcie-stats")
		opts+=""
			;;
		"get-latency-monitor-log")
		opts+=""
			;;
		"get-error-recovery-log")
		opts+=""
			;;
		"get-dev-capabilities-log")
		opts+=""
			;;
		"get-unsupported-reqs-log")
		opts+=""
			;;
		"cloud-boot-SSD-version")
		opts+=" --namespace-id= -n"
			;;
		"vs-cloud-log")
		opts+=" --namespace-id= -n"
			;;
		"vs-hw-rev-log")
		opts+=" --namespace-id= -n"
			;;
		"vs-device-waf")
		opts+=" --namespace-id= -n"
			;;
		"set-latency-monitor-feature")
		opts+=" --active_bucket_timer_threshold= -t --active_threshold_a= -a --active_threshold_b= -b --active_threshold_c= -c --active_threshold_d= -d --active_latency_config= -f --active_latency_minimum_window= -w --debug_log_trigger_enable= -r --discard_debug_log= -l --latency_monitor_feature_enable= -e"
			;;
		"cu-smart-log")
		opts+=" --uuid-index= -u"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_sfx_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b --json -j"
			;;
		"lat-stats")
		opts+=" --write -w --raw-binary -b"
			;;
		"get-bad-block")
		opts+=""
			;;
		"query-cap")
		opts+=" --raw-binary -b"
			;;
		"change-cap")
		opts+=" --cap= -c --cap-byte= -z --force -f"
			;;
		"set-feature")
		opts+=" --namespace-id= -n --feature-id= -f --value= -V --force -s"
			;;
		"get-feature")
		opts+=" --namespace-id= -n --feature-id= -f"
			;;
		"dump-evtlog")
		opts+=" --file= -f --namespace_id= -n --storage_medium= -s --parse -p --output= -O"
			;;
		"expand-cap")
		opts+=" --namespace_id= -n --namespace_size= -s --namespace_cap= -c --lbaf= -l --units= -u"
			;;
		"status")
		opts+=" --json-print -j"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_seagate_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help"|"plugin-version"|"cloud-SSD-plugin-version")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"vs-temperature-stats")
		opts+=""
			;;
		"vs-log-page-sup")
		opts+=""
			;;
		"vs-smart-add-log")
		opts+=""
			;;
		"vs-pcie-stats")
		opts+=""
			;;
		"clear-pcie-correctable-errors")
		opts+=" --save -s"
			;;
		"get-host-tele")
		opts+=" --namespace-id= -n --log_specific= -i --raw-binary -b"
			;;
		"get-ctrl-tele")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"vs-internal-log")
		opts+=" --namespace-id= -n --dump-file= -f"
			;;
		"vs-fw-activate-history")
		opts+=""
			;;
		"clear-fw-activate-history")
		opts+=" --save -s"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_shannon_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
		"set-additioal-feature")
		opts+=" --namespace-id= -n --feature-id= -f --value= -V --data-len= -l --data= -d --save -s"
			;;
		"get-additional-feature")
		opts+=" --namespace-id= -n --feature-id= -f --sel= -s --data-len= -l --raw-binary -b --cdw11= -c --human-readable -H"
			;;
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_ssstc_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b --json -j"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_toshiba_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"vs-smart-add-log")
		opts+=" --namespace-id= -n --output-file= -O --log= -l"
			;;
		"vs-internal-log")
		opts+=" --output-file= -O --prev-log -p"
			;;
		"clear-pcie-correctable-errors")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_transcend_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"healthvalue")
		opts+=""
			;;
		"badblock")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_virtium_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"save-smart-to-vtview-log")
		opts+=" --run-time= -r --freq= -f --output-file= -O --test-name= -n"
			;;
		"show-identify")
		opts+=""
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_wdc_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"cap-diag")
		opts+=" --output-file= -O --transfer-size= -s"
			;;
		"drive-log")
		opts+=" --output-file= -O"
			;;
		"get-crash-dump")
		opts+=" --output-file= -O"
			;;
		"get-pfail-dump")
		opts+=" --output-file= -O"
			;;
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
		"purge")
		opts+=""
			;;
		"purge-monitor")
		opts+=""
			;;
		"vs-internal-log")
		opts+=" --output-file= -O --transfer-size= -s --data-area= -d --type= -t --verbose -V --file-size= -f --offset= -e"
			;;
		"vs-nand-stats")
		opts+=""
			;;
		"vs-smart-add-log")
		opts+=" --interval= -i --log-page-version= -l --log-page-mask= -p --namespace-id= -n"
			;;
		"clear-pcie-correctable-errors")
		opts+=""
			;;
		"drive-essentials")
		opts+=" --dir-name= -d"
			;;
		"get-drive-status")
		opts+=""
			;;
		"clear-assert-dump")
		opts+=""
			;;
		"drive-resize")
		opts+=" --size= -s"
			;;
		"vs-fw-activate-history")
		opts+=""
			;;
		"clear-fw-activate-history")
		opts+=""
			;;
		"enc-get-log")
		opts+=" --output-file= -O --transfer-size= -s --log-id= -l"
			;;
		"vs-telemetry-controller-option")
		opts+=" --disable -d --enable -e --status -s"
			;;
		"vs-error-reason-identifier")
		opts+=" --log-id= -i --file= -O"
			;;
		"log-page-directory")
		opts+=""
			;;
		"namespace-resize")
		opts+=" --namespace-id= -n --op-option= -O"
			;;
		"vs-drive-info")
		opts+=""
			;;
		"vs-temperature-stats")
		opts+=""
			;;
		"capabilities")
		opts+=""
			;;
		"cloud-SSD-plugin-version")
		opts+=""
			;;
		"vs-pcie-stats")
		opts+=""
			;;
		"get-latency-monitor-log")
		opts+=""
			;;
		"get-error-recovery-log")
		opts+=""
			;;
		"get-dev-capabilities-log")
		opts+=""
			;;
		"get-unsupported-reqs-log")
		opts+=""
			;;
		"cloud-boot-SSD-version")
		opts+=" --namespace-id= -n"
			;;
		"vs-cloud-log")
		opts+=" --namespace-id= -n"
			;;
		"vs-hw-rev-log")
		opts+=" --namespace-id= -n"
			;;
		"vs-device-waf")
		opts+=" --namespace-id= -n"
			;;
		"set-latency-monitor-feature")
		opts+=" --active_bucket_timer_threshold= -t --active_threshold_a= -a --active_threshold_b= -b --active_threshold_c= -c --active_threshold_d= -d --active_latency_config= -f --active_latency_minimum_window= -w --debug_log_trigger_enable= -r --discard_debug_log= -l --latency_monitor_feature_enable= -e"
			;;
		"cu-smart-log")
		opts+=" --uuid-index= -u"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_ymtc_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-log-add")
		opts+=" --namespace-id= -n --raw-binary -b"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_zns_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help"|"list")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=""
			;;
		"id-ns")
		opts+=" --namespace-id= -n --vendor-specific -V --human-readable -H"
			;;
		"report-zones")
		opts+=" --namespace-id= -n --start-lba= -s --descs= -d --state= -S --verbose -V --extended -e --partial -p"
			;;
		"reset-zone")
		opts+=" --namespace-id= -n --start-lba= -s --select-all -a"
			;;
		"close-zone")
		opts+=" --namespace-id= -n --start-lba= -s --select-all -a"
			;;
		"finish-zone")
		opts+=" --namespace-id= -n --start-lba= -s --select-all -a"
			;;
		"open-zone")
		opts+=" --namespace-id= -n --start-lba= -s --zrwaa -r --select-all -a"
			;;
		"offline-zone")
		opts+=" --namespace-id= -n --start-lba= -s --select-all -a"
			;;
		"set-zone-desc")
		opts+=" --namespace-id= -n --start-lba= -s --zrwaa -r --data= -d"
			;;
		"zrwa-flush-zone")
		opts+=" --namespace-id= -n --lba= -l"
			;;
		"changed-zone-list")
		opts+=" --namespace-id= -n --rae -r"
			;;
		"zone-mgmt-recv")
		opts+=" --namespace-id= -n --start-lba= -s --zra= -z --zrasf= -S --partial -p --data-len= -l"
			;;
		"zone-mgmt-send")
		opts+=" --namespace-id= -n --start-lba= -s --zsaso -O --select-all -a --zsa= -z --data-len= -l --data= -d"
			;;
		"zone-append")
		opts+=" --namespace-id= -n --zslba= -s --data-size= -z --metadata-size= -y --data= -d --metadata= -M --limited-retry -l --force-unit-access -f --prinfo= -p --piremap -P --latency -t"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_nbft_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"show")
		opts+=" --subsystem -s --hfi -H --discovery -d --nbft-path="
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_registry_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"list")
		opts+=""
			;;
		"retrieve")
		opts+=" --attr= -a"
			;;
		"update")
		opts+=" --attr= -a --value= -V"
			;;
		"delete")
		opts+=" --attr= -a"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_feat_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"arbitration")
		opts+=" --ab= -a --lpw= -l --mpw= -m --hpw= -H --save -s --sel= -S"
			;;
		"power-mgmt")
		opts+=" --ps= -p --wh= -w --save -s --sel= -S"
			;;
		"temp-thresh")
		opts+=" --tmpth= -T --tmpsel= -m --thsel= -H --tmpthh= -M --save -s --sel= -S"
			;;
		"volatile-wc")
		opts+=" --wce -w --save -s --sel= -S"
			;;
		"num-queues")
		opts+=" --nsqr= -n --ncqr= -c --save -s --sel= -S"
			;;
		"timestamp")
		opts+=" --tstmp= -t --save -s --sel= -S"
			;;
		"hctm")
		opts+=" --tmt1= -t --tmt2= -T --save -s --sel= -S"
			;;
		"host-behavior-support")
		opts+=" --acre= -a --etdas= -e --lbafee= -l --hdisns= -H --cdfe= -c --save -s --sel= -S"
			;;
		"perf-characteristics")
		opts+=" --namespace-id= -n --attri= -a --rvspa -r --r4karl= -R --paid= -p --attrl= -A --vs-data= -V --save -s --sel= -S"
			;;
		"power-limit")
		opts+=" --plv= -p --pls= -l --uuid-index= -u --save -s --sel= -S"
			;;
		"power-thresh")
		opts+=" --ptv= -p --pts= -t --pmts= -m --ept= -e --uuid-index= -u --save -s --sel= -S"
			;;
		"power-meas")
		opts+=" --act= --pmts= --smt= --uuid-index= -u --save -s --sel= -S"
			;;
		"err-recovery")
		opts+=" --nsid= -n --tler= -t --dulbe -d --save -s --sel= -S"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_lm_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"create-cdq")
		opts+=" --size= -s --cntlid= -c --queue-type= -q --consent"
			;;
		"delete-cdq")
		opts+=" --cdqid= -C"
			;;
		"track-send")
		opts+=" --sel= -s --mos= -m --cdqid= -C --start --stop"
			;;
		"migration-send")
		opts+=" --sel= -s --cntlid= -c --stype= -t --dudmq -d --seq-ind= -S --csuuidi= -U --csvi= -V --uidx= -u --offset= -O --numd= -n --input-file= -f"
			;;
		"migration-recv")
		opts+=" --sel= -s --cntlid= -c --csuuidi= -U --csvi= -V --uidx= -u --offset= -O --numd= -n --output-file= -f --human-readable -H"
			;;
		"set-cdq")
		opts+=" --cdqid= -C --hp= -H --tpt= -T"
			;;
		"get-cdq")
		opts+=" --cdqid= -C"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_ocp_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"smart-add-log")
		opts+=""
			;;
		"latency-monitor-log")
		opts+=""
			;;
		"set-latency-monitor-feature")
		opts+=" --active_bucket_timer_threshold= -t --active_threshold_a= -a --active_threshold_b= -b --active_threshold_c= -c --active_threshold_d= -d --active_latency_config= -f --active_latency_minimum_window= -w --debug_log_trigger_enable= -r --discard_debug_log= -l --latency_monitor_feature_enable= -e"
			;;
		"internal-log")
		opts+=" --telemetry-log= -l --string-log= -s --output-file= -f --data-area= -a --telemetry-type= -t"
			;;
		"clear-fw-activate-history")
		opts+=" --no-uuid -n"
			;;
		"eol-plp-failure-mode")
		opts+=" --mode= -m --save -s --sel= -S --no-uuid -n"
			;;
		"clear-pcie-correctable-errors")
		opts+=" --no-uuid -n"
			;;
		"fw-activate-history")
		opts+=""
			;;
		"unsupported-reqs-log")
		opts+=""
			;;
		"error-recovery-log")
		opts+=""
			;;
		"device-capability-log")
		opts+=""
			;;
		"set-dssd-power-state-feature")
		opts+=" --power-state= -p --save -s --no-uuid -n"
			;;
		"get-dssd-power-state-feature")
		opts+=" --sel= -S --all -a --no-uuid -n"
			;;
		"set-plp-health-check-interval")
		opts+=" --plp_health_interval= -p --save -s --no-uuid -n"
			;;
		"get-plp-health-check-interval")
		opts+=" --sel= -S"
			;;
		"telemetry-string-log")
		opts+=" --output-file= -f"
			;;
		"set-telemetry-profile")
		opts+=" --telemetry-profile-select= -t"
			;;
		"set-dssd-async-event-config")
		opts+=" --enable-panic-notices -e --save -s"
			;;
		"get-dssd-async-event-config")
		opts+=" --sel= -S"
			;;
		"tcg-configuration-log")
		opts+=""
			;;
		"get-error-injection")
		opts+=" --sel= -s --no-uuid -n --all-ns -a"
			;;
		"set-error-injection")
		opts+=" --data= -d --number= -n --no-uuid -N --all-ns -a --type= -t --nrtdp= -r"
			;;
		"get-enable-ieee1667-silo")
		opts+=" --sel= -s --no-uuid -n"
			;;
		"set-enable-ieee1667-silo")
		opts+=" --enable -e --save -s --no-uuid -n"
			;;
		"hardware-component-log")
		opts+=" --comp-id= -i --list -l"
			;;
		"get-latency-monitor")
		opts+=" --sel= -s --namespace-id= -n --no-uuid -u"
			;;
		"get-clear-pcie-correctable-errors")
		opts+=" --sel= -s --namespace-id= -n --no-uuid -u"
			;;
		"get-telemetry-profile")
		opts+=" --sel= -s --namespace-id= -n --no-uuid -u"
			;;
		"persistent-event-log")
		opts+=" --action= -a --log_len= -l --raw-binary -b"
			;;
		"get-idle-wakeup-time")
		opts+=" --sel= -s --namespace-id= -n --no-uuid -u"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_sed_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help"|"password")
			;;
		*)
		opts+=""
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
			esac
		fi
			;;
	esac

	case "$1" in
		"discover")
		opts+=" --verbose -V --udev -u"
			;;
		"initialize")
		opts+=" --read-only -r"
			;;
		"revert")
		opts+=" --destructive -e --psid -p"
			;;
		"lock")
		opts+=" --read-only -r --ask-key -k"
			;;
		"unlock")
		opts+=" --read-only -r --ask-key -k"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

plugin_solidigm_opts () {
	local opts=""
	local compargs=""
	local vals=""
	local opt=""
	local val=""

	local nonopt_args=0
	local has_device=0
	for (( i=0; i < ${#words[@]}-1; i++ )); do
		if [[ ${words[i]} != -* ]] && [[ ${words[i]} != "=" ]]; then
			let nonopt_args+=1
			if [[ ${words[i]} == /dev/* ]]; then
				has_device=1
			fi
		fi
	done

	if [[ $nonopt_args -ge 3 ]] && [[ $has_device -eq 0 ]] && \
	   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
		opts="/dev/nvme* "
	fi

	opts+=" "
	vals+=" "

	local completing_value=0
	_nvme_detect_value_completion
	case "$1" in
		"version"|"help")
			;;
		*)
		opts+=" --verbose -v --output-format= -o --timeout= --dry-run --no-retries --no-ioctl-probing --output-format-version="
		if [[ $completing_value -eq 1 ]]; then
			case $opt in
				--output-format|-o)
				vals+=" normal json binary tabular"
					;;
				--output-format-version)
				vals+=" 1 2"
					;;
			esac
		fi
			;;
	esac

	case "$1" in
		"id-ctrl")
		opts+=" --vendor-specific -V --raw-binary -b"
			;;
		"smart-log-add")
		opts+=" --namespace-id= -n"
			;;
		"vs-smart-add-log")
		opts+=""
			;;
		"vs-internal-log")
		opts+=" --type= -t --dir-name= -d"
			;;
		"garbage-collect-log")
		opts+=""
			;;
		"market-log")
		opts+=" --raw-binary -b"
			;;
		"latency-tracking-log")
		opts+=" --enable -e --disable -d --read -r --write -w --type= -t"
			;;
		"parse-telemetry-log")
		opts+=" --host-generate= -g --controller-init -c --data-area= -d --config-file= -j --source-file= -s --jq-filter= -q"
			;;
		"clear-pcie-correctable-errors ")
		opts+=" --no-uuid -n"
			;;
		"clear-fw-activate-history")
		opts+=" --no-uuid -n"
			;;
		"vs-fw-activate-history")
		opts+=""
			;;
		"log-page-directory")
		opts+=""
			;;
		"temp-stats")
		opts+=" --raw-binary -b"
			;;
		"vs-drive-info")
		opts+=""
			;;
		"cloud-SSDplugin-version")
		opts+=""
			;;
		"workload-tracker")
		opts+=" --uuid-index= -U --enable -e --disable -d --sample-time= -s --type= -t --run-time= -r --flush-freq= -f --wall-clock -w --trigger-field= -T --trigger-threshold= -V --trigger-on-delta -D --trigger-on-latency -L"
			;;
	esac

	opts+=" -h --help"

	if [[ $vals == " " ]]; then
		COMPREPLY+=( $( compgen $compargs -W "$opts" -- $cur ) )
		[[ ${COMPREPLY-} == *= ]] && compopt -o nospace
	else
		COMPREPLY+=( $( compgen $compargs -W "$vals" -- $val ) )
	fi

	return 0
}

_nvme_subcmds () {
	local cur prev words cword
	_init_completion || return

	typeset -Ar _plugin_subcmds=(
		[amzn]="id-ctrl stats"
		[dapustor]="smart-log-add"
		[dell]="id-ctrl"
		[dera]="smart-log-add"
		[fdp]="configs usage stats events status update set-events feature"
		[huawei]="list id-ctrl"
		[ibm]="crit-log vpd persist-event-log"
		[innogrit]="get-eventlog get-cdump"
		[inspur]="nvme-vendor-log"
		[intel]="id-ctrl internal-log lat-stats set-bucket-thresholds lat-stats-tracking market-name smart-log-add temp-stats"
		[mangoboost]="id-ctrl"
		[memblaze]="smart-log-add get-pm-status set-pm-status select-download lat-stats lat-stats-print lat-log lat-log-print clear-error-log smart-log-add-x lat-set-feature-x lat-get-feature-x lat-stats-print-x lat-log-print-x perf-stats-print-x"
		[micron]="select-download vs-temperature-stats vs-pcie-stats clear-pcie-correctable-errors vs-internal-log vs-telemetry-controller-option vs-nand-stats vs-smart-ext-log vs-drive-info plugin-version cloud-SSD-plugin-version log-page-directory vs-fw-activate-history latency-tracking latency-stats latency-logs vs-smart-add-log clear-fw-activate-history vs-smbus-option cloud-boot-SSD-version vs-device-waf vs-cloud-log vs-work-load-log vs-vendor-telemetry-log smart-log id-ctrl"
		[netapp]="smdevices ontapdevices"
		[nvidia]="id-ctrl"
		[sndk]="vs-internal-log vs-nand-stats vs-smart-add-log clear-pcie-correctable-errors get-drive-status clear-assert-dump drive-resize vs-fw-activate-history clear-fw-activate-history vs-telemetry-controller-option vs-error-reason-identifier log-page-directory namespace-resize vs-drive-info vs-temperature-stats capabilities cloud-SSD-plugin-version vs-pcie-stats get-latency-monitor-log get-error-recovery-log get-dev-capabilities-log get-unsupported-reqs-log cloud-boot-SSD-version vs-cloud-log vs-hw-rev-log vs-device-waf set-latency-monitor-feature cu-smart-log"
		[sfx]="smart-log-add lat-stats get-bad-block query-cap change-cap set-feature get-feature dump-evtlog expand-cap status"
		[seagate]="vs-temperature-stats vs-log-page-sup vs-smart-add-log vs-pcie-stats clear-pcie-correctable-errors get-host-tele get-ctrl-tele vs-internal-log vs-fw-activate-history clear-fw-activate-history plugin-version cloud-SSD-plugin-version"
		[shannon]="smart-log-add set-additioal-feature get-additional-feature id-ctrl"
		[ssstc]="smart-log-add"
		[toshiba]="vs-smart-add-log vs-internal-log clear-pcie-correctable-errors"
		[transcend]="healthvalue badblock"
		[virtium]="save-smart-to-vtview-log show-identify"
		[wdc]="cap-diag drive-log get-crash-dump get-pfail-dump id-ctrl purge purge-monitor vs-internal-log vs-nand-stats vs-smart-add-log clear-pcie-correctable-errors drive-essentials get-drive-status clear-assert-dump drive-resize vs-fw-activate-history clear-fw-activate-history enc-get-log vs-telemetry-controller-option vs-error-reason-identifier log-page-directory namespace-resize vs-drive-info vs-temperature-stats capabilities cloud-SSD-plugin-version vs-pcie-stats get-latency-monitor-log get-error-recovery-log get-dev-capabilities-log get-unsupported-reqs-log cloud-boot-SSD-version vs-cloud-log vs-hw-rev-log vs-device-waf set-latency-monitor-feature cu-smart-log"
		[ymtc]="smart-log-add"
		[zns]="list id-ctrl id-ns report-zones reset-zone close-zone finish-zone open-zone offline-zone set-zone-desc zrwa-flush-zone changed-zone-list zone-mgmt-recv zone-mgmt-send zone-append"
		[nbft]="show"
		[registry]="list retrieve update delete"
		[feat]="arbitration power-mgmt temp-thresh volatile-wc num-queues timestamp hctm host-behavior-support perf-characteristics power-limit power-thresh power-meas err-recovery"
		[lm]="create-cdq delete-cdq track-send migration-send migration-recv set-cdq get-cdq"
		[ocp]="smart-add-log latency-monitor-log set-latency-monitor-feature internal-log clear-fw-activate-history eol-plp-failure-mode clear-pcie-correctable-errors fw-activate-history unsupported-reqs-log error-recovery-log device-capability-log set-dssd-power-state-feature get-dssd-power-state-feature set-plp-health-check-interval get-plp-health-check-interval telemetry-string-log set-telemetry-profile set-dssd-async-event-config get-dssd-async-event-config tcg-configuration-log get-error-injection set-error-injection get-enable-ieee1667-silo set-enable-ieee1667-silo hardware-component-log get-latency-monitor get-clear-pcie-correctable-errors get-telemetry-profile persistent-event-log get-idle-wakeup-time"
		[sed]="discover initialize revert lock unlock password"
		[solidigm]="id-ctrl smart-log-add vs-smart-add-log vs-internal-log garbage-collect-log market-log latency-tracking-log parse-telemetry-log clear-pcie-correctable-errors  clear-fw-activate-history vs-fw-activate-history log-page-directory temp-stats vs-drive-info cloud-SSDplugin-version workload-tracker"
	)

	typeset -Ar _plugin_funcs=(
		[amzn]="plugin_amzn_opts"
		[dapustor]="plugin_dapustor_opts"
		[dell]="plugin_dell_opts"
		[dera]="plugin_dera_opts"
		[fdp]="plugin_fdp_opts"
		[huawei]="plugin_huawei_opts"
		[ibm]="plugin_ibm_opts"
		[innogrit]="plugin_innogrit_opts"
		[inspur]="plugin_inspur_opts"
		[intel]="plugin_intel_opts"
		[mangoboost]="plugin_mangoboost_opts"
		[memblaze]="plugin_memblaze_opts"
		[micron]="plugin_micron_opts"
		[netapp]="plugin_netapp_opts"
		[nvidia]="plugin_nvidia_opts"
		[sndk]="plugin_sndk_opts"
		[sfx]="plugin_sfx_opts"
		[seagate]="plugin_seagate_opts"
		[shannon]="plugin_shannon_opts"
		[ssstc]="plugin_ssstc_opts"
		[toshiba]="plugin_toshiba_opts"
		[transcend]="plugin_transcend_opts"
		[virtium]="plugin_virtium_opts"
		[wdc]="plugin_wdc_opts"
		[ymtc]="plugin_ymtc_opts"
		[zns]="plugin_zns_opts"
		[nbft]="plugin_nbft_opts"
		[registry]="plugin_registry_opts"
		[feat]="plugin_feat_opts"
		[lm]="plugin_lm_opts"
		[ocp]="plugin_ocp_opts"
		[sed]="plugin_sed_opts"
		[solidigm]="plugin_solidigm_opts"
	)

	_cmds="list list-subsys id-ctrl id-ns id-ns-granularity id-ns-lba-format list-ns list-ctrl nvm-id-ctrl nvm-id-ns nvm-id-ns-lba-format primary-ctrl-caps list-secondary cmdset-ind-id-ns ns-descs id-nvmset id-uuid id-iocs id-domain list-endgrp create-ns delete-ns attach-ns detach-ns get-ns-id get-log telemetry-log fw-log changed-ns-list-log smart-log ana-log error-log effects-log endurance-log predictable-lat-log pred-lat-event-agg-log persistent-event-log endurance-event-agg-log lba-status-log resv-notif-log boot-part-log phy-rx-eom-log get-feature device-self-test self-test-log supported-log-pages fid-support-effects-log mi-cmd-support-effects-log media-unit-stat-log supported-cap-config-log mgmt-addr-list-log rotational-media-info-log changed-alloc-ns-list-log dispersed-ns-participating-nss-log reachability-groups-log reachability-associations-log host-discovery-log ave-discovery-log pull-model-ddc-req-log power-measurement-log set-feature set-property get-property format fw-commit fw-download admin-passthru io-passthru security-send security-recv get-lba-status capacity-mgmt resv-acquire resv-register resv-release resv-report dsm copy flush compare read write write-zeroes write-uncor verify sanitize sanitize-log sanitize-ns reset subsystem-reset ns-rescan show-regs set-reg get-reg top discover connect-all connect disconnect disconnect-all config dim gen-hostnqn show-hostnqn gen-dhchap-key check-dhchap-key gen-tls-key check-tls-key tls-key dir-receive dir-send virt-mgmt rpmb lockdown show-topology io-mgmt-recv io-mgmt-send nvme-mi-recv nvme-mi-send dump-command-metadata amzn dapustor dell dera fdp huawei ibm innogrit inspur intel mangoboost memblaze micron netapp nvidia sndk sfx seagate shannon ssstc toshiba transcend virtium wdc ymtc zns nbft registry feat lm ocp sed solidigm"

	if [[ ${#words[*]} -lt 3 ]]; then
		COMPREPLY+=( $(compgen -W "$_cmds" -- $cur ) )
	else
		for subcmd in "${!_plugin_subcmds[@]}"; do
			if [[ ${words[1]} == $subcmd ]]; then
				if [[ ${#words[*]} -lt 4 ]]; then
					COMPREPLY+=( $(compgen -W "${_plugin_subcmds[$subcmd]}" -- $cur ) )
				else
					func=${_plugin_funcs[$subcmd]}
					$func ${words[2]} $prev
				fi
				return 0
			fi
		done

		nvme_list_opts ${words[1]} $prev
	fi

	return 0
}

complete -o default -F _nvme_subcmds nvme
