#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2026 Micron Technology, Inc.
"""Generate the bash completion script for nvme-cli.

Input is the JSON metadata emitted by `nvme utils dump-command-metadata`, read
from a file or stdin. The command/option model is captured at runtime from the
compiled binary, so this script does no C parsing -- it only formats.

Usage:
    nvme utils dump-command-metadata | generate-completions.py \\
        --bash bash-nvme-completion.sh
    generate-completions.py model.json --bash -        # '-' writes to stdout
"""

import argparse
import json
import sys


# ---------------------------------------------------------------------------
# Model access helpers
# ---------------------------------------------------------------------------

def opt_suffix(opt):
    """'=' if the option takes an argument, else ''."""
    return "=" if opt.get("argument", "none") != "none" else ""


def opt_word(opt):
    """The completion word for an option: '--name=' or '--name'."""
    return "--" + opt["long"] + opt_suffix(opt)


def flatten(s):
    """Collapse whitespace so a multi-line description stays on one line."""
    return " ".join((s or "").split())


def has_options(cmd):
    """True if the command accepts any options."""
    return bool(cmd.get("options"))


def cmd_names(cmd):
    """Every name a command answers to: its primary name plus any alias.

    Names are whitespace-stripped, which defends against a stray space in the C
    command tables (e.g. "clear-pcie-correctable-errors ") that would otherwise
    produce a case label the argv word can never match.
    """
    names = [cmd["name"]]
    if cmd.get("alias"):
        names.append(cmd["alias"])
    return [n for n in (s.strip() for s in names) if n]


# Completion values for options the metadata carries none for. Keyed by long
# option name, applied to every command with it, so only list values that are
# uniform across all commands.
# NOTE: This is a stopgap. These should probably be defined in the C option
# definitions (OPT_VALS) so they flow through the metadata for all tooling.
VALUE_HINTS = {
    "output-format-version": ["1", "2"],
    "sel": ["0", "1", "2", "3"],
}


def command_options(cmd, scope="all"):
    """Yield options, optionally filtered by scope ("all", "global", "local").

    Hidden options are always skipped: they are accepted on the command line
    but suppressed from --help, so they should not be offered as completions.

    Options that have no enforced value set but do have a completion hint (see
    VALUE_HINTS) are yielded with that hint filled into "values".
    """
    if scope not in ("all", "global", "local"):
        raise ValueError(f"invalid scope: {scope!r}")
    for opt in cmd.get("options", []):
        if opt.get("hidden"):
            continue
        g = bool(opt.get("global"))
        if scope == "global" and not g:
            continue
        if scope == "local" and g:
            continue
        if "values" not in opt and opt["long"] in VALUE_HINTS:
            opt = dict(opt, values=VALUE_HINTS[opt["long"]])
        yield opt


def plugins(model):
    return model.get("plugins", [])


def builtin_commands(model):
    return model.get("commands", [])


# ---------------------------------------------------------------------------
# bash
# ---------------------------------------------------------------------------

BASH_HEADER = '''\
# SPDX-License-Identifier: GPL-2.0-or-later
#
# bash tab completion for the nvme command line utility
#
# This file is generated by generate-completions.py. Do not edit.

# COMPREPLY=( $(compgen ...) ) is the standard bash-completion idiom; the word
# splitting SC2207 warns about is intentional here.
# shellcheck disable=SC2207

# Helper function to detect if we're completing an option's value.
# Uses: $cur, $prev, $words, $cword (from _init_completion)
# Sets: $opt (the option name), $val (partial value), $completing_value (0 or 1)
_nvme_detect_value_completion() {
\tcompleting_value=0
\topt=""
\tval=""

\tif [[ $cur == --*=* ]]; then
\t\topt="${cur%%=*}"
\t\tval="${cur#*=}"
\t\tcompleting_value=1
\telif [[ $cur == "=" ]] && [[ $prev == --* ]]; then
\t\topt="$prev"
\t\tcompleting_value=1
\telif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == "=" ]] && [[ ${words[$cword-2]} == --* ]]; then
\t\topt="${words[$cword-2]}"
\t\tval="$cur"
\t\tcompleting_value=1
\telif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == --* ]]; then
\t\topt="$prev"
\t\tval="$cur"
\t\tcompleting_value=1
\telif [[ $cur == "" ]] && [[ $prev == --* ]]; then
\t\topt="$prev"
\t\tcompleting_value=1
\telif [[ $cur == "" ]] && [[ $prev == "=" ]]; then
\t\topt="${words[$cword-2]}"
\t\tcompleting_value=1
\telif [[ $cur == "" ]] && [[ $prev == -? ]]; then
\t\topt="$prev"
\t\tcompleting_value=1
\telif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == -? ]]; then
\t\topt="$prev"
\t\tval="$cur"
\t\tcompleting_value=1
\tfi

\t# When the option word was captured unsplit (e.g. '--output-format='), drop
\t# the trailing '=' so $opt matches the '--name|-s)' clauses below.
\topt="${opt%=}"
}
'''

BASH_FUNC_PREAMBLE = '''\

{func} () {{
\tlocal opts=""
\tlocal vals=""
\tlocal opt=""
\tlocal val=""

\tlocal nonopt_args=0
\tlocal has_device=0
\tlocal i
\tfor (( i=0; i < ${{#words[@]}}-1; i++ )); do
\t\tif [[ ${{words[i]}} != -* ]] && [[ ${{words[i]}} != "=" ]]; then
\t\t\t(( nonopt_args += 1 ))
\t\t\tif [[ ${{words[i]}} == /dev/* ]]; then
\t\t\t\thas_device=1
\t\t\tfi
\t\tfi
\tdone

\tif [[ $nonopt_args -ge {device_argpos} ]] && [[ $has_device -eq 0 ]] && \\
\t   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
\t\topts="/dev/nvme* "
\tfi

\topts+=" "
\tvals+=" "

\tlocal completing_value=0
\tlocal wantfiles=0
\t_nvme_detect_value_completion
'''

BASH_FUNC_EPILOGUE = '''\

\topts+=" -h --help"

\tif [[ $completing_value -eq 1 ]]; then
\t\tif [[ $vals != " " ]]; then
\t\t\tCOMPREPLY+=( $( compgen -W "$vals" -- "$val" ) )
\t\telif [[ $wantfiles -eq 1 ]]; then
\t\t\t: # value is a filename; let 'complete -o default' offer files
\t\telse
\t\t\t# No candidate values (e.g. a NUM or free-form string); offer
\t\t\t# nothing and suppress the filename fallback.
\t\t\tcompopt +o default
\t\tfi
\telse
\t\tCOMPREPLY+=( $( compgen -W "$opts" -- "$cur" ) )
\t\t# Suppress the trailing space only when the sole completion ends in '=',
\t\t# so the user can type the value immediately. With more than one candidate
\t\t# bash appends nothing, so nospace must not fire.
\t\t[[ ${#COMPREPLY[@]} -eq 1 && ${COMPREPLY[0]} == *= ]] && compopt -o nospace
\tfi

\treturn 0
}
'''


def wrap_words(words, indent, width=72):
    """Join words into indented lines, wrapping near `width` columns."""
    lines = []
    line = indent
    for w in words:
        if line != indent and len(line) + 1 + len(w) > width:
            lines.append(line)
            line = indent
        line += (" " if line != indent else "") + w
    if line != indent:
        lines.append(line)
    return "\n".join(lines)


def bash_option_words(opts):
    """Build the ' --name= -s ...' word list for a sequence of options."""
    out = ""
    for o in opts:
        out += " " + opt_word(o)
        if o.get("short"):
            out += " -" + o["short"]
    return out


def opt_is_file(opt):
    """True if the option's value is a filename/path we can file-complete."""
    return opt.get("metavar") in ("FILE", "DIRECTORY")


def bash_value_clause(opt):
    """A 'case $opt in' clause for an option whose value we can complete.

    Emits a clause that sets $vals (known value set) or $wantfiles (file/path
    argument). Returns '' for options with no completable value -- their value
    branch offers nothing and suppresses the filename fallback.
    """
    sel = "--" + opt["long"]
    if opt.get("short"):
        sel += "|-" + opt["short"]
    vals = opt.get("values")
    if vals:
        action = f"vals+=\" {' '.join(vals)}\""
    elif opt_is_file(opt):
        action = "wantfiles=1"
    else:
        return ""
    return (f"\t\t\t\t\t{sel})\n"
            f"\t\t\t\t\t\t{action}\n"
            f"\t\t\t\t\t\t;;\n")


def emit_bash_plugin(out, commands, func, device_argpos):
    out.write(BASH_FUNC_PREAMBLE.format(func=func, device_argpos=device_argpos))

    # Shared clause: global options + value completion. version/help and commands
    # that accept no options at all match here as a no-op, so they are not
    # offered the global options; every other command falls through to '*)'.
    # Skipped entirely when nothing global exists to offer.
    globals_src = next((c for c in commands
                        if list(command_options(c, "global"))), None)
    if globals_src:
        global_opts = list(command_options(globals_src, "global"))
        skip = "|".join(['"version"', '"help"'] +
                        [f'"{n}"' for c in commands if not has_options(c)
                         for n in cmd_names(c)])
        words = bash_option_words(global_opts)
        out.write(f'\tcase "$1" in\n\t\t{skip})\n\t\t\t;;\n\t\t*)\n')
        out.write(f'\t\t\topts+="{words}"\n')
        clauses = "".join(bash_value_clause(o) for o in global_opts)
        if clauses:
            out.write('\t\t\tif [[ $completing_value -eq 1 ]]; then\n\t\t\t\tcase $opt in\n')
            out.write(clauses)
            out.write('\t\t\t\tesac\n\t\t\tfi\n')
        out.write('\t\t\t;;\n\tesac\n\n')

    # Per-command specific options, plus value clauses for any that carry values.
    # Built up first so the enclosing case is omitted when no command has locals.
    body = ""
    for c in commands:
        if not has_options(c):
            continue
        locals_ = list(command_options(c, "local"))
        words = bash_option_words(locals_)
        value_clauses = "".join(bash_value_clause(o) for o in locals_)
        # Only globals? The shared '*)' clause already covers it; no clause needed.
        if not words and not value_clauses:
            continue
        label = "|".join(f'"{n}"' for n in cmd_names(c))
        body += f'\t\t{label})\n\t\t\topts+="{words}"\n'
        if value_clauses:
            body += '\t\t\tif [[ $completing_value -eq 1 ]]; then\n\t\t\t\tcase $opt in\n'
            body += value_clauses
            body += '\t\t\t\tesac\n\t\t\tfi\n'
        body += '\t\t\t;;\n'
    if body:
        out.write('\tcase "$1" in\n')
        out.write(body)
        out.write('\tesac\n')

    out.write(BASH_FUNC_EPILOGUE)


def bash_func_name(plugin):
    return "plugin_%s_opts" % plugin.replace("-", "_")


def generate_bash(model, out):
    out.write(BASH_HEADER)

    emit_bash_plugin(out, builtin_commands(model), "nvme_list_opts", 2)
    for p in plugins(model):
        emit_bash_plugin(out, p["commands"], bash_func_name(p["name"]), 3)

    # Dispatcher.
    out.write("\n_nvme_subcmds () {\n"
              "\tlocal cur prev words cword\n"
              "\t_init_completion || return\n"
              "\n"
              "\ttypeset -Ar _plugin_subcmds=(\n")
    for p in plugins(model):
        names = " ".join(n for c in p["commands"] for n in cmd_names(c))
        out.write(f'\t\t[{p["name"]}]="{names}"\n')
    out.write("\t)\n\n\ttypeset -Ar _plugin_funcs=(\n")
    for p in plugins(model):
        out.write(f'\t\t[{p["name"]}]="{bash_func_name(p["name"])}"\n')
    out.write("\t)\n\n\tlocal -a _cmds=(\n")
    cmds = ([n for c in builtin_commands(model) for n in cmd_names(c)] +
            [p["name"] for p in plugins(model)])
    out.write(wrap_words(cmds, "\t\t"))
    out.write("\n\t)\n\n"
              "\tlocal func subcmd\n"
              "\tif [[ ${#words[*]} -lt 3 ]]; then\n"
              "\t\tCOMPREPLY+=( $(compgen -W \"${_cmds[*]}\" -- \"$cur\" ) )\n"
              "\telse\n"
              "\t\tfor subcmd in \"${!_plugin_subcmds[@]}\"; do\n"
              "\t\t\tif [[ ${words[1]} == \"$subcmd\" ]]; then\n"
              "\t\t\t\tif [[ ${#words[*]} -lt 4 ]]; then\n"
              "\t\t\t\t\tCOMPREPLY+=( $(compgen -W \"${_plugin_subcmds[$subcmd]}\" -- \"$cur\" ) )\n"
              "\t\t\t\telse\n"
              "\t\t\t\t\tfunc=${_plugin_funcs[$subcmd]}\n"
              "\t\t\t\t\t$func \"${words[2]}\" \"$prev\"\n"
              "\t\t\t\tfi\n"
              "\t\t\t\treturn 0\n"
              "\t\t\tfi\n"
              "\t\tdone\n"
              "\n"
              "\t\tnvme_list_opts \"${words[1]}\" \"$prev\"\n"
              "\tfi\n"
              "\n"
              "\treturn 0\n"
              "}\n"
              "\ncomplete -o default -F _nvme_subcmds nvme\n")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def open_out(path):
    return sys.stdout if path == "-" else open(path, "w")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", nargs="?", default="-",
                    help="JSON model file, or '-' for stdin (default)")
    ap.add_argument("--bash", metavar="FILE", required=True,
                    help="write bash completion to FILE ('-' for stdout)")
    args = ap.parse_args()

    if args.input == "-":
        model = json.load(sys.stdin)
    else:
        with open(args.input) as src:
            model = json.load(src)

    out = open_out(args.bash)
    try:
        generate_bash(model, out)
    finally:
        if out is not sys.stdout:
            out.close()


if __name__ == "__main__":
    main()
