#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2026 Micron Technology, Inc.
"""Generate shell completion scripts for nvme-cli.

Input is the JSON metadata emitted by `nvme utils dump-command-metadata`, read
from a file or stdin. The command/option model is captured at runtime from the
compiled binary, so this script does no C parsing -- it only formats.

Usage:
    nvme utils dump-command-metadata | generate-completions.py \\
        --bash bash-nvme-completion.sh --zsh _nvme \\
        --powershell nvme-completion.ps1
    generate-completions.py model.json --bash -        # '-' writes to stdout
"""

import argparse
import json
import sys


# ---------------------------------------------------------------------------
# Model access helpers
# ---------------------------------------------------------------------------

def opt_suffix(opt):
    """'=' if the option takes an argument, else ''."""
    return "=" if opt.get("argument", "none") != "none" else ""


def opt_word(opt):
    """The completion word for an option: '--name=' or '--name'."""
    return "--" + opt["long"] + opt_suffix(opt)


def flatten(s):
    """Collapse whitespace so a multi-line description stays on one line."""
    return " ".join((s or "").split())


def has_options(cmd):
    """True if the command accepts any options."""
    return bool(cmd.get("options"))


def cmd_names(cmd):
    """Every name a command answers to: its primary name plus any alias.

    Names are whitespace-stripped, which defends against a stray space in the C
    command tables (e.g. "clear-pcie-correctable-errors ") that would otherwise
    produce a case label the argv word can never match.
    """
    names = [cmd["name"]]
    if cmd.get("alias"):
        names.append(cmd["alias"])
    return [n for n in (s.strip() for s in names) if n]


# Completion values for options the metadata carries none for. Keyed by long
# option name, applied to every command with it, so only list values that are
# uniform across all commands.
# NOTE: This is a stopgap. These should probably be defined in the C option
# definitions (OPT_VALS) so they flow through the metadata for all tooling.
VALUE_HINTS = {
    "output-format-version": ["1", "2"],
    "sel": ["0", "1", "2", "3"],
}


def command_options(cmd, scope="all"):
    """Yield options, optionally filtered by scope ("all", "global", "local").

    Hidden options are always skipped: they are accepted on the command line
    but suppressed from --help, so they should not be offered as completions.

    Options that have no enforced value set but do have a completion hint (see
    VALUE_HINTS) are yielded with that hint filled into "values".
    """
    if scope not in ("all", "global", "local"):
        raise ValueError(f"invalid scope: {scope!r}")
    for opt in cmd.get("options", []):
        if opt.get("hidden"):
            continue
        g = bool(opt.get("global"))
        if scope == "global" and not g:
            continue
        if scope == "local" and g:
            continue
        if "values" not in opt and opt["long"] in VALUE_HINTS:
            opt = dict(opt, values=VALUE_HINTS[opt["long"]])
        yield opt


def plugins(model):
    return model.get("plugins", [])


def builtin_commands(model):
    return model.get("commands", [])


# ---------------------------------------------------------------------------
# bash
# ---------------------------------------------------------------------------

BASH_HEADER = '''\
# SPDX-License-Identifier: GPL-2.0-or-later
#
# bash tab completion for the nvme command line utility
#
# This file is generated by generate-completions.py. Do not edit.

# COMPREPLY=( $(compgen ...) ) is the standard bash-completion idiom; the word
# splitting SC2207 warns about is intentional here.
# shellcheck disable=SC2207

# Helper function to detect if we're completing an option's value.
# Uses: $cur, $prev, $words, $cword (from _init_completion)
# Sets: $opt (the option name), $val (partial value), $completing_value (0 or 1)
_nvme_detect_value_completion() {
\tcompleting_value=0
\topt=""
\tval=""

\tif [[ $cur == --*= ]]; then
\t\topt="${cur%=}"
\t\tcompleting_value=1
\telif [[ $cur == "=" ]] && [[ $prev == --* ]]; then
\t\topt="$prev"
\t\tcompleting_value=1
\telif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == "=" ]] && [[ ${words[$cword-2]} == --* ]]; then
\t\topt="${words[$cword-2]}"
\t\tval="$cur"
\t\tcompleting_value=1
\telif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == --* ]]; then
\t\topt="$prev"
\t\tval="$cur"
\t\tcompleting_value=1
\telif [[ $cur == "" ]] && [[ $prev == --* ]]; then
\t\topt="$prev"
\t\tcompleting_value=1
\telif [[ $cur == "" ]] && [[ $prev == "=" ]]; then
\t\topt="${words[$cword-2]}"
\t\tcompleting_value=1
\telif [[ $cur == "" ]] && [[ $prev == -? ]]; then
\t\topt="$prev"
\t\tcompleting_value=1
\telif [[ $cur != -* ]] && [[ $cur != "" ]] && [[ $prev == -? ]]; then
\t\topt="$prev"
\t\tval="$cur"
\t\tcompleting_value=1
\tfi
}
'''

BASH_FUNC_PREAMBLE = '''\

{func} () {{
\tlocal opts=""
\tlocal vals=""
\tlocal opt=""
\tlocal val=""

\tlocal nonopt_args=0
\tlocal has_device=0
\tlocal i
\tfor (( i=0; i < ${{#words[@]}}-1; i++ )); do
\t\tif [[ ${{words[i]}} != -* ]] && [[ ${{words[i]}} != "=" ]]; then
\t\t\t(( nonopt_args += 1 ))
\t\t\tif [[ ${{words[i]}} == /dev/* ]]; then
\t\t\t\thas_device=1
\t\t\tfi
\t\tfi
\tdone

\tif [[ $nonopt_args -ge {device_argpos} ]] && [[ $has_device -eq 0 ]] && \\
\t   [[ "$1" != "help" ]] && [[ "$1" != "version" ]]; then
\t\topts="/dev/nvme* "
\tfi

\topts+=" "
\tvals+=" "

\tlocal completing_value=0
\tlocal wantfiles=0
\t_nvme_detect_value_completion
'''

BASH_FUNC_EPILOGUE = '''\

\topts+=" -h --help"

\tif [[ $completing_value -eq 1 ]]; then
\t\tif [[ $vals != " " ]]; then
\t\t\tCOMPREPLY+=( $( compgen -W "$vals" -- "$val" ) )
\t\telif [[ $wantfiles -eq 1 ]]; then
\t\t\t: # value is a filename; let 'complete -o default' offer files
\t\telse
\t\t\t# No candidate values (e.g. a NUM or free-form string); offer
\t\t\t# nothing and suppress the filename fallback.
\t\t\tcompopt +o default
\t\tfi
\telse
\t\tCOMPREPLY+=( $( compgen -W "$opts" -- "$cur" ) )
\t\t# Suppress the trailing space only when the sole completion ends in '=',
\t\t# so the user can type the value immediately. With more than one candidate
\t\t# bash appends nothing, so nospace must not fire.
\t\t[[ ${#COMPREPLY[@]} -eq 1 && ${COMPREPLY[0]} == *= ]] && compopt -o nospace
\tfi

\treturn 0
}
'''


def wrap_words(words, indent, width=72):
    """Join words into indented lines, wrapping near `width` columns."""
    lines = []
    line = indent
    for w in words:
        if line != indent and len(line) + 1 + len(w) > width:
            lines.append(line)
            line = indent
        line += (" " if line != indent else "") + w
    if line != indent:
        lines.append(line)
    return "\n".join(lines)


def bash_option_words(opts):
    """Build the ' --name= -s ...' word list for a sequence of options."""
    out = ""
    for o in opts:
        out += " " + opt_word(o)
        if o.get("short"):
            out += " -" + o["short"]
    return out


def opt_is_file(opt):
    """True if the option's value is a filename/path we can file-complete."""
    return opt.get("metavar") in ("FILE", "DIRECTORY")


def bash_value_clause(opt):
    """A 'case $opt in' clause for an option whose value we can complete.

    Emits a clause that sets $vals (known value set) or $wantfiles (file/path
    argument). Returns '' for options with no completable value -- their value
    branch offers nothing and suppresses the filename fallback.
    """
    sel = "--" + opt["long"]
    if opt.get("short"):
        sel += "|-" + opt["short"]
    vals = opt.get("values")
    if vals:
        action = f"vals+=\" {' '.join(vals)}\""
    elif opt_is_file(opt):
        action = "wantfiles=1"
    else:
        return ""
    return (f"\t\t\t\t\t{sel})\n"
            f"\t\t\t\t\t\t{action}\n"
            f"\t\t\t\t\t\t;;\n")


def emit_bash_plugin(out, commands, func, device_argpos):
    out.write(BASH_FUNC_PREAMBLE.format(func=func, device_argpos=device_argpos))

    # Shared clause: global options + value completion. version/help and commands
    # that accept no options at all match here as a no-op, so they are not
    # offered the global options; every other command falls through to '*)'.
    # Skipped entirely when nothing global exists to offer.
    globals_src = next((c for c in commands
                        if list(command_options(c, "global"))), None)
    if globals_src:
        global_opts = list(command_options(globals_src, "global"))
        skip = "|".join(['"version"', '"help"'] +
                        [f'"{n}"' for c in commands if not has_options(c)
                         for n in cmd_names(c)])
        words = bash_option_words(global_opts)
        out.write(f'\tcase "$1" in\n\t\t{skip})\n\t\t\t;;\n\t\t*)\n')
        out.write(f'\t\t\topts+="{words}"\n')
        clauses = "".join(bash_value_clause(o) for o in global_opts)
        if clauses:
            out.write('\t\t\tif [[ $completing_value -eq 1 ]]; then\n\t\t\t\tcase $opt in\n')
            out.write(clauses)
            out.write('\t\t\t\tesac\n\t\t\tfi\n')
        out.write('\t\t\t;;\n\tesac\n\n')

    # Per-command specific options, plus value clauses for any that carry values.
    # Built up first so the enclosing case is omitted when no command has locals.
    body = ""
    for c in commands:
        if not has_options(c):
            continue
        locals_ = list(command_options(c, "local"))
        words = bash_option_words(locals_)
        value_clauses = "".join(bash_value_clause(o) for o in locals_)
        # Only globals? The shared '*)' clause already covers it; no clause needed.
        if not words and not value_clauses:
            continue
        label = "|".join(f'"{n}"' for n in cmd_names(c))
        body += f'\t\t{label})\n\t\t\topts+="{words}"\n'
        if value_clauses:
            body += '\t\t\tif [[ $completing_value -eq 1 ]]; then\n\t\t\t\tcase $opt in\n'
            body += value_clauses
            body += '\t\t\t\tesac\n\t\t\tfi\n'
        body += '\t\t\t;;\n'
    if body:
        out.write('\tcase "$1" in\n')
        out.write(body)
        out.write('\tesac\n')

    out.write(BASH_FUNC_EPILOGUE)


def bash_func_name(plugin):
    return "plugin_%s_opts" % plugin.replace("-", "_")


def generate_bash(model, out):
    out.write(BASH_HEADER)

    emit_bash_plugin(out, builtin_commands(model), "nvme_list_opts", 2)
    for p in plugins(model):
        emit_bash_plugin(out, p["commands"], bash_func_name(p["name"]), 3)

    # Dispatcher.
    out.write("\n_nvme_subcmds () {\n"
              "\tlocal cur prev words cword\n"
              "\t_init_completion || return\n"
              "\n"
              "\ttypeset -Ar _plugin_subcmds=(\n")
    for p in plugins(model):
        names = " ".join(n for c in p["commands"] for n in cmd_names(c))
        out.write(f'\t\t[{p["name"]}]="{names}"\n')
    out.write("\t)\n\n\ttypeset -Ar _plugin_funcs=(\n")
    for p in plugins(model):
        out.write(f'\t\t[{p["name"]}]="{bash_func_name(p["name"])}"\n')
    out.write("\t)\n\n\tlocal -a _cmds=(\n")
    cmds = ([n for c in builtin_commands(model) for n in cmd_names(c)] +
            [p["name"] for p in plugins(model)])
    out.write(wrap_words(cmds, "\t\t"))
    out.write("\n\t)\n\n"
              "\tlocal func subcmd\n"
              "\tif [[ ${#words[*]} -lt 3 ]]; then\n"
              "\t\tCOMPREPLY+=( $(compgen -W \"${_cmds[*]}\" -- \"$cur\" ) )\n"
              "\telse\n"
              "\t\tfor subcmd in \"${!_plugin_subcmds[@]}\"; do\n"
              "\t\t\tif [[ ${words[1]} == \"$subcmd\" ]]; then\n"
              "\t\t\t\tif [[ ${#words[*]} -lt 4 ]]; then\n"
              "\t\t\t\t\tCOMPREPLY+=( $(compgen -W \"${_plugin_subcmds[$subcmd]}\" -- \"$cur\" ) )\n"
              "\t\t\t\telse\n"
              "\t\t\t\t\tfunc=${_plugin_funcs[$subcmd]}\n"
              "\t\t\t\t\t$func \"${words[2]}\" \"$prev\"\n"
              "\t\t\t\tfi\n"
              "\t\t\t\treturn 0\n"
              "\t\t\tfi\n"
              "\t\tdone\n"
              "\n"
              "\t\tnvme_list_opts \"${words[1]}\" \"$prev\"\n"
              "\tfi\n"
              "\n"
              "\treturn 0\n"
              "}\n"
              "\ncomplete -o default -F _nvme_subcmds nvme\n")


# ---------------------------------------------------------------------------
# zsh
# ---------------------------------------------------------------------------

ZSH_HEADER = '''\
#compdef _nvme nvme
# SPDX-License-Identifier: GPL-2.0-or-later
#
# zsh completions for the nvme command-line interface
#
# This file is generated by generate-completions.py. Do not edit.
'''

ZSH_HELPERS = '''\
\t# Describe options, giving those ending in '=' no trailing space.
\t_nvme_describe() {
\t\tlocal desc="$1"
\t\tlocal -a opts=("${(@P)2}")
\t\tlocal -a eq_opts noeq_opts
\t\tlocal opt

\t\tfor opt in "${opts[@]}"; do
\t\t\tif [[ "${opt%%:*}" == *= ]]; then
\t\t\t\teq_opts+=("$opt")
\t\t\telse
\t\t\t\tnoeq_opts+=("$opt")
\t\t\tfi
\t\tdone

\t\t(( ${#noeq_opts} )) && _describe -t options "$desc" noeq_opts
\t\t(( ${#eq_opts} )) && _describe -t eq-options "$desc" eq_opts -S ''
\t}

\t# Complete the value of an option (both --opt=val and --opt val forms).
\t# Usage: _nvme_complete_option_value "long|short" value1 value2 ...
\t_nvme_complete_option_value() {
\t\tlocal -a opts=("${(s:|:)1}")
\t\tshift
\t\tlocal -a values=("$@")

\t\tlocal opt
\t\tfor opt in "${opts[@]}"; do
\t\t\tif [[ ${words[CURRENT]} == ${opt}=* ]]; then
\t\t\t\t_values '' "${values[@]}"
\t\t\t\treturn 0
\t\t\tfi
\t\t\tif [[ ${words[CURRENT-1]} == "${opt}" ]]; then
\t\t\t\t_values '' "${values[@]}"
\t\t\t\treturn 0
\t\t\tfi
\t\tdone
\t\treturn 1
\t}
'''


def zsh_escape(s):
    """Escape a string for inclusion inside a zsh '...' single-quoted string."""
    return (s or "").replace("'", "'\\''")


def zsh_var(plugin, cmd):
    name = "_"
    if plugin:
        name += plugin.replace("-", "_") + "_"
    name += cmd.replace("-", "_")
    return name


def emit_zsh_value_completions(out, tab, cmd):
    for o in command_options(cmd):
        vals = o.get("values")
        if not vals:
            continue
        sel = "--" + o["long"]
        if o.get("short"):
            sel += "|-" + o["short"]
        out.write(f'{tab}_nvme_complete_option_value "{sel}" '
                  f'{" ".join(vals)} && return\n')


def emit_zsh_command_clause(out, tab, path, cmd):
    out.write(f"{tab}({cmd['name']})\n")
    if not has_options(cmd):
        # No options to offer, but still complete a device argument.
        out.write(f"{tab}compadd -- /dev/nvme*(N)\n")
        out.write(f"{tab}\t;;\n")
        return

    emit_zsh_value_completions(out, tab, cmd)

    var = zsh_var(path, cmd["name"])
    out.write(f"{tab}local {var}\n{tab}{var}=(\n")
    for o in command_options(cmd):
        desc = zsh_escape(flatten(o.get("description")))
        out.write(f"{tab}\t--{o['long']}{opt_suffix(o)}':{desc}'\n")
        if o.get("short"):
            out.write(f"{tab}\t-{o['short']}':alias for --{o['long']}'\n")
    out.write(f"{tab})\n")
    out.write(f"{tab}_arguments '*:: :->subcmds'\n")
    label = f"nvme {path + ' ' if path else ''}{cmd['name']} options"
    out.write(f'{tab}_nvme_describe "{label}" {var}\n')
    out.write(f"{tab}compadd -- /dev/nvme*(N)\n")
    out.write(f"{tab}\t;;\n")


def generate_zsh(model, out):
    out.write(ZSH_HEADER)
    out.write("\n_nvme () {\n\tlocal -a _cmds\n\t_cmds=(\n")
    for c in builtin_commands(model):
        out.write(f"\t\t'{c['name']}:{zsh_escape(flatten(c.get('description')))}'\n")
    for p in plugins(model):
        out.write(f"\t\t'{p['name']}:{zsh_escape(flatten(p.get('description')))}'\n")
    out.write("\t)\n\n")

    out.write(ZSH_HELPERS)

    out.write("\n\t_arguments '*:: :->subcmds' && return 0\n\n"
              "\tif (( CURRENT == 1 )); then\n"
              "\t\t_describe -t commands \"nvme subcommands\" _cmds\n"
              "\t\treturn\n"
              "\telif (( CURRENT > 2 )); then\n"
              "\t\tcase ${words[1]} in\n")

    for p in plugins(model):
        out.write(f"\t\t({p['name']})\n\t\t\tcase ${{words[2]}} in\n")
        for c in p["commands"]:
            emit_zsh_command_clause(out, "\t\t\t", p["name"], c)
        out.write("\t\t\t(*)\n\t\t\t\t_files\n\t\t\t\t;;\n")
        out.write("\t\t\tesac\n\t\t\t;;\n")

    for c in builtin_commands(model):
        emit_zsh_command_clause(out, "\t\t", None, c)

    out.write("\t\t(*)\n\t\t\t_files\n\t\t\t;;\n"
              "\t\tesac\n\t\treturn\n\tfi\n\n"
              "\t_files\n}\n")


# ---------------------------------------------------------------------------
# powershell
# ---------------------------------------------------------------------------

PS_HEADER = '''\
# SPDX-License-Identifier: GPL-2.0-or-later
#
# PowerShell argument completer for the nvme command line utility.
#
# This file is generated by generate-completions.py. Do not edit.
# Source it from your PowerShell profile to enable completion.
'''

PS_COMPLETER = '''
Register-ArgumentCompleter -Native -CommandName nvme -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    # tokens[0] is 'nvme'. Determine command context.
    $nonOpt = @($tokens[1..($tokens.Count-1)] | Where-Object { $_ -notlike '-*' })

    # Completing the (sub)command name itself.
    if ($nonOpt.Count -le 1) {
        return $script:NvmeCommands | Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    $first = $nonOpt[0]
    $key = $null
    if ($script:NvmePluginCommands.ContainsKey($first)) {
        if ($nonOpt.Count -le 2) {
            return $script:NvmePluginCommands[$first] | Where-Object { $_ -like "$wordToComplete*" } |
                ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
        }
        $key = "$first $($nonOpt[1])"
    } else {
        $key = $first
    }

    if ($script:NvmeOptions.ContainsKey($key)) {
        return $script:NvmeOptions[$key] | Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }
    }
}
'''


def ps_escape(s):
    """Escape for a PowerShell single-quoted string (double the quote)."""
    return (s or "").replace("'", "''")


def ps_command_options(cmd):
    """The ('--opt', '-s', ...) option list for one command."""
    words = []
    if has_options(cmd):
        for o in command_options(cmd):
            words.append("'--%s'" % o["long"])
            if o.get("short"):
                words.append("'-%s'" % o["short"])
    return ", ".join(words)


def generate_powershell(model, out):
    out.write(PS_HEADER)

    out.write("\n$script:NvmeCommands = @(\n")
    for c in builtin_commands(model):
        out.write(f"    '{c['name']}'\n")
    for p in plugins(model):
        out.write(f"    '{p['name']}'\n")
    out.write(")\n")

    out.write("\n$script:NvmePluginCommands = @{\n")
    for p in plugins(model):
        names = ", ".join("'%s'" % c["name"] for c in p["commands"])
        out.write(f"    '{p['name']}' = @({names})\n")
    out.write("}\n")

    out.write("\n$script:NvmeOptions = @{\n")
    for c in builtin_commands(model):
        out.write(f"    '{ps_escape(c['name'])}' = @({ps_command_options(c)})\n")
    for p in plugins(model):
        for c in p["commands"]:
            key = ps_escape("%s %s" % (p["name"], c["name"]))
            out.write(f"    '{key}' = @({ps_command_options(c)})\n")
    out.write("}\n")

    out.write(PS_COMPLETER)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

GENERATORS = {"bash": generate_bash, "zsh": generate_zsh,
              "powershell": generate_powershell}


def open_out(path):
    return sys.stdout if path == "-" else open(path, "w")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", nargs="?", default="-",
                    help="JSON model file, or '-' for stdin (default)")
    ap.add_argument("--bash", metavar="FILE", help="write bash completion to FILE")
    ap.add_argument("--zsh", metavar="FILE", help="write zsh completion to FILE")
    ap.add_argument("--powershell", metavar="FILE",
                    help="write PowerShell completion to FILE")
    args = ap.parse_args()

    if args.input == "-":
        model = json.load(sys.stdin)
    else:
        with open(args.input) as src:
            model = json.load(src)

    requested = [(s, getattr(args, s)) for s in GENERATORS if getattr(args, s)]
    if not requested:
        ap.error("specify at least one of --bash/--zsh/--powershell")

    for shell, path in requested:
        out = open_out(path)
        try:
            GENERATORS[shell](model, out)
        finally:
            if out is not sys.stdout:
                out.close()


if __name__ == "__main__":
    main()
