# SPDX-License-Identifier: GPL-2.0-or-later
#
# PowerShell argument completer for the nvme command line utility.
#
# This file is generated by `nvme gen-completions powershell`. Do not edit.
# Source it from your PowerShell profile to enable completion.

$script:NvmeCommands = @(
    'list'
    'list-subsys'
    'id-ctrl'
    'id-ns'
    'id-ns-granularity'
    'id-ns-lba-format'
    'list-ns'
    'list-ctrl'
    'nvm-id-ctrl'
    'nvm-id-ns'
    'nvm-id-ns-lba-format'
    'primary-ctrl-caps'
    'list-secondary'
    'cmdset-ind-id-ns'
    'ns-descs'
    'id-nvmset'
    'id-uuid'
    'id-iocs'
    'id-domain'
    'list-endgrp'
    'create-ns'
    'delete-ns'
    'attach-ns'
    'detach-ns'
    'get-ns-id'
    'get-log'
    'telemetry-log'
    'fw-log'
    'changed-ns-list-log'
    'smart-log'
    'ana-log'
    'error-log'
    'effects-log'
    'endurance-log'
    'predictable-lat-log'
    'pred-lat-event-agg-log'
    'persistent-event-log'
    'endurance-event-agg-log'
    'lba-status-log'
    'resv-notif-log'
    'boot-part-log'
    'phy-rx-eom-log'
    'get-feature'
    'device-self-test'
    'self-test-log'
    'supported-log-pages'
    'fid-support-effects-log'
    'mi-cmd-support-effects-log'
    'media-unit-stat-log'
    'supported-cap-config-log'
    'mgmt-addr-list-log'
    'rotational-media-info-log'
    'changed-alloc-ns-list-log'
    'dispersed-ns-participating-nss-log'
    'reachability-groups-log'
    'reachability-associations-log'
    'host-discovery-log'
    'ave-discovery-log'
    'pull-model-ddc-req-log'
    'power-measurement-log'
    'set-feature'
    'set-property'
    'get-property'
    'format'
    'fw-commit'
    'fw-download'
    'admin-passthru'
    'io-passthru'
    'security-send'
    'security-recv'
    'get-lba-status'
    'capacity-mgmt'
    'resv-acquire'
    'resv-register'
    'resv-release'
    'resv-report'
    'dsm'
    'copy'
    'flush'
    'compare'
    'read'
    'write'
    'write-zeroes'
    'write-uncor'
    'verify'
    'sanitize'
    'sanitize-log'
    'sanitize-ns'
    'reset'
    'subsystem-reset'
    'ns-rescan'
    'show-regs'
    'set-reg'
    'get-reg'
    'top'
    'discover'
    'connect-all'
    'connect'
    'disconnect'
    'disconnect-all'
    'config'
    'dim'
    'gen-hostnqn'
    'show-hostnqn'
    'gen-dhchap-key'
    'check-dhchap-key'
    'gen-tls-key'
    'check-tls-key'
    'tls-key'
    'dir-receive'
    'dir-send'
    'virt-mgmt'
    'rpmb'
    'lockdown'
    'show-topology'
    'io-mgmt-recv'
    'io-mgmt-send'
    'nvme-mi-recv'
    'nvme-mi-send'
    'gen-completions'
    'amzn'
    'dapustor'
    'dell'
    'dera'
    'fdp'
    'huawei'
    'ibm'
    'innogrit'
    'inspur'
    'intel'
    'mangoboost'
    'memblaze'
    'micron'
    'netapp'
    'nvidia'
    'sndk'
    'sfx'
    'seagate'
    'shannon'
    'ssstc'
    'toshiba'
    'transcend'
    'virtium'
    'wdc'
    'ymtc'
    'zns'
    'nbft'
    'feat'
    'lm'
    'ocp'
    'sed'
    'solidigm'
)

$script:NvmePluginCommands = @{
    'amzn' = @('id-ctrl', 'stats')
    'dapustor' = @('smart-log-add')
    'dell' = @('id-ctrl')
    'dera' = @('smart-log-add')
    'fdp' = @('configs', 'usage', 'stats', 'events', 'status', 'update', 'set-events', 'feature')
    'huawei' = @('list', 'id-ctrl')
    'ibm' = @('crit-log', 'vpd', 'persist-event-log')
    'innogrit' = @('get-eventlog', 'get-cdump')
    'inspur' = @('nvme-vendor-log')
    'intel' = @('id-ctrl', 'internal-log', 'lat-stats', 'set-bucket-thresholds', 'lat-stats-tracking', 'market-name', 'smart-log-add', 'temp-stats')
    'mangoboost' = @('id-ctrl')
    'memblaze' = @('smart-log-add', 'get-pm-status', 'set-pm-status', 'select-download', 'lat-stats', 'lat-stats-print', 'lat-log', 'lat-log-print', 'clear-error-log', 'smart-log-add-x', 'lat-set-feature-x', 'lat-get-feature-x', 'lat-stats-print-x', 'lat-log-print-x', 'perf-stats-print-x')
    'micron' = @('select-download', 'vs-temperature-stats', 'vs-pcie-stats', 'clear-pcie-correctable-errors', 'vs-internal-log', 'vs-telemetry-controller-option', 'vs-nand-stats', 'vs-smart-ext-log', 'vs-drive-info', 'plugin-version', 'cloud-SSD-plugin-version', 'log-page-directory', 'vs-fw-activate-history', 'latency-tracking', 'latency-stats', 'latency-logs', 'vs-smart-add-log', 'clear-fw-activate-history', 'vs-smbus-option', 'cloud-boot-SSD-version', 'vs-device-waf', 'vs-cloud-log', 'vs-work-load-log', 'vs-vendor-telemetry-log', 'smart-log', 'id-ctrl')
    'netapp' = @('smdevices', 'ontapdevices')
    'nvidia' = @('id-ctrl')
    'sndk' = @('vs-internal-log', 'vs-nand-stats', 'vs-smart-add-log', 'clear-pcie-correctable-errors', 'get-drive-status', 'clear-assert-dump', 'drive-resize', 'vs-fw-activate-history', 'clear-fw-activate-history', 'vs-telemetry-controller-option', 'vs-error-reason-identifier', 'log-page-directory', 'namespace-resize', 'vs-drive-info', 'vs-temperature-stats', 'capabilities', 'cloud-SSD-plugin-version', 'vs-pcie-stats', 'get-latency-monitor-log', 'get-error-recovery-log', 'get-dev-capabilities-log', 'get-unsupported-reqs-log', 'cloud-boot-SSD-version', 'vs-cloud-log', 'vs-hw-rev-log', 'vs-device-waf', 'set-latency-monitor-feature', 'cu-smart-log')
    'sfx' = @('smart-log-add', 'lat-stats', 'get-bad-block', 'query-cap', 'change-cap', 'set-feature', 'get-feature', 'dump-evtlog', 'expand-cap', 'status')
    'seagate' = @('vs-temperature-stats', 'vs-log-page-sup', 'vs-smart-add-log', 'vs-pcie-stats', 'clear-pcie-correctable-errors', 'get-host-tele', 'get-ctrl-tele', 'vs-internal-log', 'vs-fw-activate-history', 'clear-fw-activate-history', 'plugin-version', 'cloud-SSD-plugin-version')
    'shannon' = @('smart-log-add', 'set-additioal-feature', 'get-additional-feature', 'id-ctrl')
    'ssstc' = @('smart-log-add')
    'toshiba' = @('vs-smart-add-log', 'vs-internal-log', 'clear-pcie-correctable-errors')
    'transcend' = @('healthvalue', 'badblock')
    'virtium' = @('save-smart-to-vtview-log', 'show-identify')
    'wdc' = @('cap-diag', 'drive-log', 'get-crash-dump', 'get-pfail-dump', 'id-ctrl', 'purge', 'purge-monitor', 'vs-internal-log', 'vs-nand-stats', 'vs-smart-add-log', 'clear-pcie-correctable-errors', 'drive-essentials', 'get-drive-status', 'clear-assert-dump', 'drive-resize', 'vs-fw-activate-history', 'clear-fw-activate-history', 'enc-get-log', 'vs-telemetry-controller-option', 'vs-error-reason-identifier', 'log-page-directory', 'namespace-resize', 'vs-drive-info', 'vs-temperature-stats', 'capabilities', 'cloud-SSD-plugin-version', 'vs-pcie-stats', 'get-latency-monitor-log', 'get-error-recovery-log', 'get-dev-capabilities-log', 'get-unsupported-reqs-log', 'cloud-boot-SSD-version', 'vs-cloud-log', 'vs-hw-rev-log', 'vs-device-waf', 'set-latency-monitor-feature', 'cu-smart-log')
    'ymtc' = @('smart-log-add')
    'zns' = @('list', 'id-ctrl', 'id-ns', 'report-zones', 'reset-zone', 'close-zone', 'finish-zone', 'open-zone', 'offline-zone', 'set-zone-desc', 'zrwa-flush-zone', 'changed-zone-list', 'zone-mgmt-recv', 'zone-mgmt-send', 'zone-append')
    'nbft' = @('show')
    'feat' = @('arbitration', 'power-mgmt', 'temp-thresh', 'volatile-wc', 'num-queues', 'timestamp', 'hctm', 'host-behavior-support', 'perf-characteristics', 'power-limit', 'power-thresh', 'power-meas', 'err-recovery')
    'lm' = @('create-cdq', 'delete-cdq', 'track-send', 'migration-send', 'migration-recv', 'set-cdq', 'get-cdq')
    'ocp' = @('smart-add-log', 'latency-monitor-log', 'set-latency-monitor-feature', 'internal-log', 'clear-fw-activate-history', 'eol-plp-failure-mode', 'clear-pcie-correctable-errors', 'fw-activate-history', 'unsupported-reqs-log', 'error-recovery-log', 'device-capability-log', 'set-dssd-power-state-feature', 'get-dssd-power-state-feature', 'set-plp-health-check-interval', 'get-plp-health-check-interval', 'telemetry-string-log', 'set-telemetry-profile', 'set-dssd-async-event-config', 'get-dssd-async-event-config', 'tcg-configuration-log', 'get-error-injection', 'set-error-injection', 'get-enable-ieee1667-silo', 'set-enable-ieee1667-silo', 'hardware-component-log', 'get-latency-monitor', 'get-clear-pcie-correctable-errors', 'get-telemetry-profile', 'persistent-event-log', 'get-idle-wakeup-time')
    'sed' = @('discover', 'initialize', 'revert', 'lock', 'unlock', 'password')
    'solidigm' = @('id-ctrl', 'smart-log-add', 'vs-smart-add-log', 'vs-internal-log', 'garbage-collect-log', 'market-log', 'latency-tracking-log', 'parse-telemetry-log', 'clear-pcie-correctable-errors ', 'clear-fw-activate-history', 'vs-fw-activate-history', 'log-page-directory', 'temp-stats', 'vs-drive-info', 'cloud-SSDplugin-version', 'workload-tracker')
}

$script:NvmeOptions = @{
    'list' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'list-subsys' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-ns' = @('--namespace-id', '-n', '--force', '--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-ns-granularity' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-ns-lba-format' = @('--lba-format-index', '-i', '--uuid-index', '-U', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'list-ns' = @('--namespace-id', '-n', '--csi', '-y', '--all', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'list-ctrl' = @('--cntid', '-c', '--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nvm-id-ctrl' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nvm-id-ns' = @('--namespace-id', '-n', '--uuid-index', '-U', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nvm-id-ns-lba-format' = @('--lba-format-index', '-i', '--uuid-index', '-U', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'primary-ctrl-caps' = @('--cntlid', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'list-secondary' = @('--cntid', '-c', '--num-entries', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'cmdset-ind-id-ns' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ns-descs' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-nvmset' = @('--nvmset_id', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-uuid' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-iocs' = @('--controller-id', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'id-domain' = @('--dom-id', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'list-endgrp' = @('--endgrp-id', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'create-ns' = @('--ish', '-I', '--nsze', '-s', '--ncap', '-c', '--flbas', '-f', '--dps', '-d', '--nmic', '-m', '--anagrp-id', '-a', '--nvmset-id', '-i', '--endg-id', '-e', '--block-size', '-b', '--csi', '-y', '--lbstm', '-l', '--nphndls', '-n', '--nsze-si', '-S', '--ncap-si', '-C', '--azr', '-z', '--rar', '-r', '--ror', '-O', '--rnumzrwa', '-u', '--phndls', '-p', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'delete-ns' = @('--ish', '-I', '--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'attach-ns' = @('--ish', '-I', '--namespace-id', '-n', '--controllers', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'detach-ns' = @('--ish', '-I', '--namespace-id', '-n', '--controllers', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'get-ns-id' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'get-log' = @('--ish', '-I', '--namespace-id', '-n', '--log-id', '-i', '--log-len', '-l', '--aen', '-a', '--lpo', '-L', '--lsp', '-s', '--lsi', '-S', '--rae', '-r', '--uuid-index', '-U', '--raw-binary', '-b', '--csi', '-y', '--ot', '-O', '--xfer-len', '-x', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'telemetry-log' = @('--output-file', '-O', '--host-generate', '-g', '--controller-init', '-c', '--data-area', '-d', '--rae', '-r', '--mcda', '-m', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fw-log' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'changed-ns-list-log' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'smart-log' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ana-log' = @('--groups', '-g', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'error-log' = @('--log-entries', '-e', '--raw-binary', '-b', '--valid-entry', '-V', '--sqid', '-S', '--status', '-s', '--lba', '-l', '--namespace-id', '-n', '--trtype', '-t', '--csi', '-c', '--opcode', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'effects-log' = @('--raw-binary', '-b', '--csi', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'endurance-log' = @('--group-id', '-g', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'predictable-lat-log' = @('--nvmset-id', '-i', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'pred-lat-event-agg-log' = @('--log-entries', '-e', '--rae', '-r', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'persistent-event-log' = @('--action', '-a', '--log_len', '-l', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'endurance-event-agg-log' = @('--log-entries', '-e', '--rae', '-r', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lba-status-log' = @('--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'resv-notif-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'boot-part-log' = @('--lsp', '-s', '--output-file', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'phy-rx-eom-log' = @('--lsp', '-s', '--controller', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'get-feature' = @('--feature-id', '-f', '--namespace-id', '-n', '--sel', '-s', '--data-len', '-l', '--raw-binary', '-b', '--cdw11', '-c', '--uuid-index', '-U', '--changed', '-C', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'device-self-test' = @('--ish', '-I', '--namespace-id', '-n', '--self-test-code', '-s', '--wait', '-w', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'self-test-log' = @('--dst-entries', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'supported-log-pages' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fid-support-effects-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'mi-cmd-support-effects-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'media-unit-stat-log' = @('--domain-id', '-d', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'supported-cap-config-log' = @('--domain-id', '-d', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'mgmt-addr-list-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'rotational-media-info-log' = @('--endg-id', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'changed-alloc-ns-list-log' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dispersed-ns-participating-nss-log' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'reachability-groups-log' = @('--groups-only', '-g', '--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'reachability-associations-log' = @('--associations-only', '-a', '--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'host-discovery-log' = @('--all-host-entries', '-a', '--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ave-discovery-log' = @('--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'pull-model-ddc-req-log' = @('--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'power-measurement-log' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'set-feature' = @('--namespace-id', '-n', '--feature-id', '-f', '--value', '-V', '--cdw12', '-c', '--uuid-index', '-U', '--data-len', '-l', '--data', '-d', '--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'set-property' = @('--offset', '-O', '--value', '-V', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'get-property' = @('--offset', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'format' = @('--ish', '-I', '--namespace-id', '-n', '--lbaf', '-l', '--ses', '-s', '--pi', '-i', '--pil', '-p', '--ms', '-m', '--reset', '-r', '--force', '--block-size', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fw-commit' = @('--ish', '-I', '--slot', '-s', '--action', '-a', '--bpid', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fw-download' = @('--fw', '-f', '--ish', '-I', '--xfer', '-x', '--offset', '-O', '--progress', '-p', '--ignore-ovr', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'admin-passthru' = @('--opcode', '-O', '--flags', '-f', '--prefill', '-p', '--rsvd', '-R', '--namespace-id', '-n', '--data-len', '-l', '--metadata-len', '-m', '--cdw2', '-2', '--cdw3', '-3', '--cdw10', '-4', '--cdw11', '-5', '--cdw12', '-6', '--cdw13', '-7', '--cdw14', '-8', '--cdw15', '-9', '--input-file', '-i', '--metadata', '-M', '--raw-binary', '-b', '--show-command', '-s', '--read', '-r', '--write', '-w', '--latency', '-T', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'io-passthru' = @('--opcode', '-O', '--flags', '-f', '--prefill', '-p', '--rsvd', '-R', '--namespace-id', '-n', '--data-len', '-l', '--metadata-len', '-m', '--cdw2', '-2', '--cdw3', '-3', '--cdw10', '-4', '--cdw11', '-5', '--cdw12', '-6', '--cdw13', '-7', '--cdw14', '-8', '--cdw15', '-9', '--input-file', '-i', '--metadata', '-M', '--raw-binary', '-b', '--show-command', '-s', '--read', '-r', '--write', '-w', '--latency', '-T', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'security-send' = @('--ish', '-I', '--namespace-id', '-n', '--file', '-f', '--nssf', '-N', '--secp', '-p', '--spsp', '-s', '--tl', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'security-recv' = @('--ish', '-I', '--namespace-id', '-n', '--size', '-x', '--nssf', '-N', '--secp', '-p', '--spsp', '-s', '--al', '-t', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'get-lba-status' = @('--ish', '-I', '--namespace-id', '-n', '--start-lba', '-s', '--max-dw', '-m', '--action', '-a', '--range-len', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'capacity-mgmt' = @('--ish', '-I', '--operation', '-O', '--element-id', '-i', '--cap-lower', '-l', '--cap-upper', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'resv-acquire' = @('--namespace-id', '-n', '--crkey', '-c', '--prkey', '-p', '--rtype', '-t', '--racqa', '-a', '--iekey', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'resv-register' = @('--namespace-id', '-n', '--crkey', '-c', '--nrkey', '-k', '--rrega', '-r', '--cptpl', '-p', '--iekey', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'resv-release' = @('--namespace-id', '-n', '--crkey', '-c', '--rtype', '-t', '--rrela', '-a', '--iekey', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'resv-report' = @('--namespace-id', '-n', '--numd', '-d', '--eds', '-e', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dsm' = @('--namespace-id', '-n', '--ctx-attrs', '-a', '--blocks', '-b', '--slbs', '-s', '--ad', '-d', '--idw', '-w', '--idr', '-r', '--cdw11', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'copy' = @('--namespace-id', '-n', '--sdlba', '-d', '--slbs', '-s', '--blocks', '-b', '--snsids', '-N', '--sopts', '-O', '--limited-retry', '-l', '--force-unit-access', '-f', '--prinfow', '-p', '--prinfor', '-P', '--ref-tag', '-r', '--expected-ref-tags', '-R', '--app-tag', '-a', '--expected-app-tags', '-A', '--app-tag-mask', '-m', '--expected-app-tag-masks', '-M', '--dir-type', '-T', '--dir-spec', '-S', '--format', '-F', '--storage-tag', '-t', '--storage-tag-check', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'flush' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'compare' = @('--namespace-id', '-n', '--start-block', '-s', '--block-count', '-c', '--block-size', '-b', '--data-size', '-z', '--metadata-size', '-y', '--ref-tag', '-r', '--data', '-d', '--metadata', '-M', '--prinfo', '-p', '--app-tag-mask', '-m', '--app-tag', '-a', '--storage-tag', '-g', '--limited-retry', '-l', '--force-unit-access', '-f', '--storage-tag-check', '-C', '--dir-type', '-T', '--dir-spec', '-S', '--dsm', '-D', '--show-command', '-V', '--latency', '-t', '--force', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'read' = @('--namespace-id', '-n', '--start-block', '-s', '--block-count', '-c', '--block-size', '-b', '--data-size', '-z', '--metadata-size', '-y', '--ref-tag', '-r', '--data', '-d', '--metadata', '-M', '--prinfo', '-p', '--app-tag-mask', '-m', '--app-tag', '-a', '--storage-tag', '-g', '--limited-retry', '-l', '--force-unit-access', '-f', '--storage-tag-check', '-C', '--dir-type', '-T', '--dir-spec', '-S', '--dsm', '-D', '--show-command', '-V', '--latency', '-t', '--force', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'write' = @('--namespace-id', '-n', '--start-block', '-s', '--block-count', '-c', '--block-size', '-b', '--data-size', '-z', '--metadata-size', '-y', '--ref-tag', '-r', '--data', '-d', '--metadata', '-M', '--prinfo', '-p', '--app-tag-mask', '-m', '--app-tag', '-a', '--storage-tag', '-g', '--limited-retry', '-l', '--force-unit-access', '-f', '--storage-tag-check', '-C', '--dir-type', '-T', '--dir-spec', '-S', '--dsm', '-D', '--show-command', '-V', '--latency', '-t', '--force', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'write-zeroes' = @('--namespace-id', '-n', '--start-block', '-s', '--block-count', '-c', '--dir-type', '-T', '--deac', '-d', '--limited-retry', '-l', '--force-unit-access', '-f', '--prinfo', '-p', '--ref-tag', '-r', '--app-tag-mask', '-m', '--app-tag', '-a', '--storage-tag', '-S', '--storage-tag-check', '-C', '--dir-spec', '-D', '--namespace-zeroes', '-Z', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'write-uncor' = @('--namespace-id', '-n', '--start-block', '-s', '--block-count', '-c', '--dir-type', '-T', '--dir-spec', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'verify' = @('--namespace-id', '-n', '--start-block', '-s', '--block-count', '-c', '--limited-retry', '-l', '--force-unit-access', '-f', '--prinfo', '-p', '--ref-tag', '-r', '--app-tag', '-a', '--app-tag-mask', '-m', '--storage-tag', '-S', '--storage-tag-check', '-C', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sanitize' = @('--ish', '-I', '--no-dealloc', '-d', '--oipbp', '-i', '--owpass', '-n', '--ause', '-u', '--sanact', '-a', '--ovrpat', '-p', '--emvs', '-e', '--wait', '-w', '--repeat', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sanitize-log' = @('--rae', '-r', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sanitize-ns' = @('--ish', '-I', '--ause', '-u', '--sanact', '-a', '--emvs', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'reset' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'subsystem-reset' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ns-rescan' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'show-regs' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'set-reg' = @('--offset', '-O', '--value', '-V', '--mmio32', '-m', '--intms', '--intmc', '--cc', '--csts', '--nssr', '--aqa', '--asq', '--acq', '--bprsel', '--bpmbl', '--cmbmsc', '--nssd', '--pmrctl', '--pmrmscl', '--pmrmscu', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'get-reg' = @('--offset', '-O', '--cap', '--vs', '--cmbloc', '--cmbsz', '--bpinfo', '--cmbsts', '--cmbebs', '--cmbswtp', '--crto', '--pmrcap', '--pmrsts', '--pmrebs', '--pmrswtp', '--intms', '--intmc', '--cc', '--csts', '--nssr', '--aqa', '--asq', '--acq', '--bprsel', '--bpmbl', '--cmbmsc', '--nssd', '--pmrctl', '--pmrmscl', '--pmrmscu', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'top' = @('--delay', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'discover' = @('--transport', '-t', '--nqn', '-n', '--traddr', '-a', '--trsvcid', '-s', '--host-traddr', '-w', '--host-iface', '-f', '--hostnqn', '-q', '--hostid', '-I', '--dhchap-secret', '-S', '--dhchap-ctrl-secret', '-C', '--keyring', '--tls-key', '--tls-key-identity', '--nr-io-queues', '-i', '--nr-write-queues', '-W', '--nr-poll-queues', '-P', '--queue-size', '-Q', '--keep-alive-tmo', '-k', '--reconnect-delay', '-c', '--ctrl-loss-tmo', '-l', '--fast_io_fail_tmo', '-F', '--tos', '-T', '--tls_key', '--duplicate-connect', '-D', '--disable-sqflow', '--hdr-digest', '-g', '--data-digest', '-G', '--tls', '--concat', '--device', '-d', '--raw', '-r', '--persistent', '-p', '--quiet', '--config', '-J', '--dump-config', '-O', '--force', '--nbft', '--no-nbft', '--owner', '--nbft-path', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'connect-all' = @('--transport', '-t', '--nqn', '-n', '--traddr', '-a', '--trsvcid', '-s', '--host-traddr', '-w', '--host-iface', '-f', '--hostnqn', '-q', '--hostid', '-I', '--dhchap-secret', '-S', '--dhchap-ctrl-secret', '-C', '--keyring', '--tls-key', '--tls-key-identity', '--nr-io-queues', '-i', '--nr-write-queues', '-W', '--nr-poll-queues', '-P', '--queue-size', '-Q', '--keep-alive-tmo', '-k', '--reconnect-delay', '-c', '--ctrl-loss-tmo', '-l', '--fast_io_fail_tmo', '-F', '--tos', '-T', '--tls_key', '--duplicate-connect', '-D', '--disable-sqflow', '--hdr-digest', '-g', '--data-digest', '-G', '--tls', '--concat', '--device', '-d', '--raw', '-r', '--persistent', '-p', '--quiet', '--config', '-J', '--dump-config', '-O', '--force', '--nbft', '--no-nbft', '--owner', '--nbft-path', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'connect' = @('--transport', '-t', '--nqn', '-n', '--traddr', '-a', '--trsvcid', '-s', '--host-traddr', '-w', '--host-iface', '-f', '--hostnqn', '-q', '--hostid', '-I', '--dhchap-secret', '-S', '--dhchap-ctrl-secret', '-C', '--keyring', '--tls-key', '--tls-key-identity', '--nr-io-queues', '-i', '--nr-write-queues', '-W', '--nr-poll-queues', '-P', '--queue-size', '-Q', '--keep-alive-tmo', '-k', '--reconnect-delay', '-c', '--ctrl-loss-tmo', '-l', '--fast_io_fail_tmo', '-F', '--tos', '-T', '--tls_key', '--duplicate-connect', '-D', '--disable-sqflow', '--hdr-digest', '-g', '--data-digest', '-G', '--tls', '--concat', '--config', '-J', '--owner', '--dump-config', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'disconnect' = @('--nqn', '-n', '--device', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'disconnect-all' = @('--transport', '-t', '--owner', '--force', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'config' = @('--transport', '-t', '--nqn', '-n', '--traddr', '-a', '--trsvcid', '-s', '--host-traddr', '-w', '--host-iface', '-f', '--hostnqn', '-q', '--hostid', '-I', '--dhchap-secret', '-S', '--dhchap-ctrl-secret', '-C', '--keyring', '--tls-key', '--tls-key-identity', '--nr-io-queues', '-i', '--nr-write-queues', '-W', '--nr-poll-queues', '-P', '--queue-size', '-Q', '--keep-alive-tmo', '-k', '--reconnect-delay', '-c', '--ctrl-loss-tmo', '-l', '--fast_io_fail_tmo', '-F', '--tos', '-T', '--tls_key', '--duplicate-connect', '-D', '--disable-sqflow', '--hdr-digest', '-g', '--data-digest', '-G', '--tls', '--concat', '--config', '-J', '--scan', '-R', '--modify', '-M', '--dump', '-O', '--update', '-U', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dim' = @('--nqn', '-n', '--device', '-d', '--task', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'gen-hostnqn' = @()
    'show-hostnqn' = @()
    'gen-dhchap-key' = @('--secret', '-s', '--key-length', '-l', '--nqn', '-n', '--hmac', '-m', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'check-dhchap-key' = @('--key', '-k', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'gen-tls-key' = @('--keyring', '-k', '--keytype', '-t', '--hostnqn', '-n', '--subsysnqn', '-c', '--secret', '-s', '--keyfile', '-f', '--hmac', '-m', '--identity', '-I', '--insert', '-i', '--compat', '-C', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'check-tls-key' = @('--keyring', '-k', '--keytype', '-t', '--hostnqn', '-n', '--subsysnqn', '-c', '--keydata', '-d', '--keyfile', '-f', '--identity', '-I', '--insert', '-i', '--compat', '-C', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'tls-key' = @('--keyring', '-k', '--keytype', '-t', '--keyfile', '-f', '--import', '-i', '--export', '-e', '--revoke', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dir-receive' = @('--namespace-id', '-n', '--data-len', '-l', '--raw-binary', '-b', '--dir-type', '-D', '--dir-spec', '-S', '--dir-oper', '-O', '--req-resource', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dir-send' = @('--namespace-id', '-n', '--data-len', '-l', '--dir-type', '-D', '--target-dir', '-T', '--dir-spec', '-S', '--dir-oper', '-O', '--endir', '-e', '--raw-binary', '-b', '--input-file', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'virt-mgmt' = @('--cntlid', '-c', '--rt', '-r', '--act', '-a', '--nr', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'rpmb' = @('--cmd', '-c', '--msgfile', '-f', '--keyfile', '-g', '--key', '-k', '--msg', '-d', '--address', '-o', '--blocks', '-b', '--target', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lockdown' = @('--ofi', '-O', '--ifc', '-f', '--prhbt', '-p', '--scp', '-s', '--uuid', '-U', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'show-topology' = @('--ranking', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'io-mgmt-recv' = @('--namespace-id', '-n', '--mos', '-s', '--mo', '-m', '--data', '-d', '--data-len', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'io-mgmt-send' = @('--namespace-id', '-n', '--mos', '-s', '--mo', '-m', '--data', '-d', '--data-len', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nvme-mi-recv' = @('--opcode', '-O', '--namespace-id', '-n', '--data-len', '-l', '--nmimt', '-m', '--nmd0', '-0', '--nmd1', '-1', '--input-file', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nvme-mi-send' = @('--opcode', '-O', '--namespace-id', '-n', '--data-len', '-l', '--nmimt', '-m', '--nmd0', '-0', '--nmd1', '-1', '--input-file', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'gen-completions' = @()
    'amzn id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'amzn stats' = @('--details', '-d', '--interval', '-i', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dapustor smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--json', '-j', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dell id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'dera smart-log-add' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp configs' = @('--endgrp-id', '-e', '--raw-binary', '-b', '--human-readable', '-H', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp usage' = @('--endgrp-id', '-e', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp stats' = @('--endgrp-id', '-e', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp events' = @('--endgrp-id', '-e', '--host-events', '-E', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp status' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp update' = @('--namespace-id', '-n', '--pids', '-p', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp set-events' = @('--namespace-id', '-n', '--placement-handle', '-p', '--enable', '-e', '--save', '-s', '--event-types', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'fdp feature' = @('--endgrp-id', '-e', '--enable-conf-idx', '-c', '--disable', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'huawei list' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'huawei id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ibm crit-log' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ibm vpd' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ibm persist-event-log' = @('--action', '-a', '--log_len', '-l', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'innogrit get-eventlog' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'innogrit get-cdump' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'inspur nvme-vendor-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel internal-log' = @('--log', '-l', '--region', '-r', '--nlognum', '-m', '--namespace-id', '-n', '--output-file', '-O', '--verbose-nlog', '-V', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel lat-stats' = @('--write', '-w', '--raw-binary', '-b', '--json', '-j', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel set-bucket-thresholds' = @('--write', '-w', '--bucket-thresholds', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel lat-stats-tracking' = @('--enable', '-e', '--disable', '-d')
    'intel market-name' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--json', '-j', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'intel temp-stats' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'mangoboost id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze get-pm-status' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze set-pm-status' = @('--value', '-V', '--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze select-download' = @('--fw', '-f', '--select', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-stats' = @('--enable', '-e', '--disable', '-d')
    'memblaze lat-stats-print' = @('--write', '-w', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-log' = @('--param', '-p', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-log-print' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze clear-error-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze smart-log-add-x' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-set-feature-x' = @('--sel-perf-log', '-s', '--set-commands-mask', '-m', '--set-read-threshold', '-r', '--set-write-threshold', '-w', '--set-trim-threshold', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-get-feature-x' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-stats-print-x' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze lat-log-print-x' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'memblaze perf-stats-print-x' = @('--duration', '-d', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron select-download' = @('--fw', '-f', '--select', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-temperature-stats' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-pcie-stats' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron clear-pcie-correctable-errors' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-internal-log' = @('--type', '-t', '--package', '-p', '--data_area', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-telemetry-controller-option' = @('--option', '-O', '--select', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-nand-stats' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-smart-ext-log' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-drive-info' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron plugin-version' = @()
    'micron cloud-SSD-plugin-version' = @()
    'micron log-page-directory' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-fw-activate-history' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron latency-tracking' = @('--option', '-O', '--command', '-c', '--threshold', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron latency-stats' = @('--command', '-c', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron latency-logs' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-smart-add-log' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron clear-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-smbus-option' = @('--option', '-O', '--value', '-V', '--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron cloud-boot-SSD-version' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-device-waf' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-cloud-log' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-work-load-log' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron vs-vendor-telemetry-log' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron smart-log' = @('--format', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'micron id-ctrl' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'netapp smdevices' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'netapp ontapdevices' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nvidia id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-internal-log' = @('--output-file', '-O', '--transfer-size', '-s', '--data-area', '-d', '--type', '-t', '--verbose', '-V', '--file-size', '-f', '--offset', '-e')
    'sndk vs-nand-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-smart-add-log' = @('--interval', '-i', '--log-page-version', '-l', '--log-page-mask', '-p', '--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk clear-pcie-correctable-errors' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk get-drive-status' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk clear-assert-dump' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk drive-resize' = @('--size', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk clear-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-telemetry-controller-option' = @('--disable', '-d', '--enable', '-e', '--status', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-error-reason-identifier' = @('--log-id', '-i', '--file', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk log-page-directory' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk namespace-resize' = @('--namespace-id', '-n', '--op-option', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-drive-info' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-temperature-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk capabilities' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk cloud-SSD-plugin-version' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-pcie-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk get-latency-monitor-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk get-error-recovery-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk get-dev-capabilities-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk get-unsupported-reqs-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk cloud-boot-SSD-version' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-cloud-log' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-hw-rev-log' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk vs-device-waf' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk set-latency-monitor-feature' = @('--active_bucket_timer_threshold', '-t', '--active_threshold_a', '-a', '--active_threshold_b', '-b', '--active_threshold_c', '-c', '--active_threshold_d', '-d', '--active_latency_config', '-f', '--active_latency_minimum_window', '-w', '--debug_log_trigger_enable', '-r', '--discard_debug_log', '-l', '--latency_monitor_feature_enable', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sndk cu-smart-log' = @('--uuid-index', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--json', '-j', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx lat-stats' = @('--write', '-w', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx get-bad-block' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx query-cap' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx change-cap' = @('--cap', '-c', '--cap-byte', '-z', '--force', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx set-feature' = @('--namespace-id', '-n', '--feature-id', '-f', '--value', '-V', '--force', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx get-feature' = @('--namespace-id', '-n', '--feature-id', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx dump-evtlog' = @('--file', '-f', '--namespace_id', '-n', '--storage_medium', '-s', '--parse', '-p', '--output', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx expand-cap' = @('--namespace_id', '-n', '--namespace_size', '-s', '--namespace_cap', '-c', '--lbaf', '-l', '--units', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sfx status' = @('--json-print', '-j', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate vs-temperature-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate vs-log-page-sup' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate vs-smart-add-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate vs-pcie-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate clear-pcie-correctable-errors' = @('--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate get-host-tele' = @('--namespace-id', '-n', '--log_specific', '-i', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate get-ctrl-tele' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate vs-internal-log' = @('--namespace-id', '-n', '--dump-file', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate vs-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate clear-fw-activate-history' = @('--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'seagate plugin-version' = @()
    'seagate cloud-SSD-plugin-version' = @()
    'shannon smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'shannon set-additioal-feature' = @('--namespace-id', '-n', '--feature-id', '-f', '--value', '-V', '--data-len', '-l', '--data', '-d', '--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'shannon get-additional-feature' = @('--namespace-id', '-n', '--feature-id', '-f', '--sel', '-s', '--data-len', '-l', '--raw-binary', '-b', '--cdw11', '-c', '--human-readable', '-H', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'shannon id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ssstc smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--json', '-j', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'toshiba vs-smart-add-log' = @('--namespace-id', '-n', '--output-file', '-O', '--log', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'toshiba vs-internal-log' = @('--output-file', '-O', '--prev-log', '-p', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'toshiba clear-pcie-correctable-errors' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'transcend healthvalue' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'transcend badblock' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'virtium save-smart-to-vtview-log' = @('--run-time', '-r', '--freq', '-f', '--output-file', '-O', '--test-name', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'virtium show-identify' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc cap-diag' = @('--output-file', '-O', '--transfer-size', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc drive-log' = @('--output-file', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-crash-dump' = @('--output-file', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-pfail-dump' = @('--output-file', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc purge' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc purge-monitor' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-internal-log' = @('--output-file', '-O', '--transfer-size', '-s', '--data-area', '-d', '--type', '-t', '--verbose', '-V', '--file-size', '-f', '--offset', '-e')
    'wdc vs-nand-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-smart-add-log' = @('--interval', '-i', '--log-page-version', '-l', '--log-page-mask', '-p', '--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc clear-pcie-correctable-errors' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc drive-essentials' = @('--dir-name', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-drive-status' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc clear-assert-dump' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc drive-resize' = @('--size', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc clear-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc enc-get-log' = @('--output-file', '-O', '--transfer-size', '-s', '--log-id', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-telemetry-controller-option' = @('--disable', '-d', '--enable', '-e', '--status', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-error-reason-identifier' = @('--log-id', '-i', '--file', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc log-page-directory' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc namespace-resize' = @('--namespace-id', '-n', '--op-option', '-O', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-drive-info' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-temperature-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc capabilities' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc cloud-SSD-plugin-version' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-pcie-stats' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-latency-monitor-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-error-recovery-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-dev-capabilities-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc get-unsupported-reqs-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc cloud-boot-SSD-version' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-cloud-log' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-hw-rev-log' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc vs-device-waf' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc set-latency-monitor-feature' = @('--active_bucket_timer_threshold', '-t', '--active_threshold_a', '-a', '--active_threshold_b', '-b', '--active_threshold_c', '-c', '--active_threshold_d', '-d', '--active_latency_config', '-f', '--active_latency_minimum_window', '-w', '--debug_log_trigger_enable', '-r', '--discard_debug_log', '-l', '--latency_monitor_feature_enable', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'wdc cu-smart-log' = @('--uuid-index', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ymtc smart-log-add' = @('--namespace-id', '-n', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns list' = @()
    'zns id-ctrl' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns id-ns' = @('--namespace-id', '-n', '--vendor-specific', '-V', '--human-readable', '-H', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns report-zones' = @('--namespace-id', '-n', '--start-lba', '-s', '--descs', '-d', '--state', '-S', '--verbose', '-V', '--extended', '-e', '--partial', '-p', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns reset-zone' = @('--namespace-id', '-n', '--start-lba', '-s', '--select-all', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns close-zone' = @('--namespace-id', '-n', '--start-lba', '-s', '--select-all', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns finish-zone' = @('--namespace-id', '-n', '--start-lba', '-s', '--select-all', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns open-zone' = @('--namespace-id', '-n', '--start-lba', '-s', '--zrwaa', '-r', '--select-all', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns offline-zone' = @('--namespace-id', '-n', '--start-lba', '-s', '--select-all', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns set-zone-desc' = @('--namespace-id', '-n', '--start-lba', '-s', '--zrwaa', '-r', '--data', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns zrwa-flush-zone' = @('--namespace-id', '-n', '--lba', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns changed-zone-list' = @('--namespace-id', '-n', '--rae', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns zone-mgmt-recv' = @('--namespace-id', '-n', '--start-lba', '-s', '--zra', '-z', '--zrasf', '-S', '--partial', '-p', '--data-len', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns zone-mgmt-send' = @('--namespace-id', '-n', '--start-lba', '-s', '--zsaso', '-O', '--select-all', '-a', '--zsa', '-z', '--data-len', '-l', '--data', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'zns zone-append' = @('--namespace-id', '-n', '--zslba', '-s', '--data-size', '-z', '--metadata-size', '-y', '--data', '-d', '--metadata', '-M', '--limited-retry', '-l', '--force-unit-access', '-f', '--prinfo', '-p', '--piremap', '-P', '--latency', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'nbft show' = @('--subsystem', '-s', '--hfi', '-H', '--discovery', '-d', '--nbft-path', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat arbitration' = @('--ab', '-a', '--lpw', '-l', '--mpw', '-m', '--hpw', '-H', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat power-mgmt' = @('--ps', '-p', '--wh', '-w', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat temp-thresh' = @('--tmpth', '-T', '--tmpsel', '-m', '--thsel', '-H', '--tmpthh', '-M', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat volatile-wc' = @('--wce', '-w', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat num-queues' = @('--nsqr', '-n', '--ncqr', '-c', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat timestamp' = @('--tstmp', '-t', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat hctm' = @('--tmt1', '-t', '--tmt2', '-T', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat host-behavior-support' = @('--acre', '-a', '--etdas', '-e', '--lbafee', '-l', '--hdisns', '-H', '--cdfe', '-c', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat perf-characteristics' = @('--namespace-id', '-n', '--attri', '-a', '--rvspa', '-r', '--r4karl', '-R', '--paid', '-p', '--attrl', '-A', '--vs-data', '-V', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat power-limit' = @('--plv', '-p', '--pls', '-l', '--uuid-index', '-u', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat power-thresh' = @('--ptv', '-p', '--pts', '-t', '--pmts', '-m', '--ept', '-e', '--uuid-index', '-u', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat power-meas' = @('--act', '--pmts', '--smt', '--uuid-index', '-u', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'feat err-recovery' = @('--nsid', '-n', '--tler', '-t', '--dulbe', '-d', '--save', '-s', '--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm create-cdq' = @('--size', '-s', '--cntlid', '-c', '--queue-type', '-q', '--consent', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm delete-cdq' = @('--cdqid', '-C', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm track-send' = @('--sel', '-s', '--mos', '-m', '--cdqid', '-C', '--start', '--stop', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm migration-send' = @('--sel', '-s', '--cntlid', '-c', '--stype', '-t', '--dudmq', '-d', '--seq-ind', '-S', '--csuuidi', '-U', '--csvi', '-V', '--uidx', '-u', '--offset', '-O', '--numd', '-n', '--input-file', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm migration-recv' = @('--sel', '-s', '--cntlid', '-c', '--csuuidi', '-U', '--csvi', '-V', '--uidx', '-u', '--offset', '-O', '--numd', '-n', '--output-file', '-f', '--human-readable', '-H', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm set-cdq' = @('--cdqid', '-C', '--hp', '-H', '--tpt', '-T', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'lm get-cdq' = @('--cdqid', '-C', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp smart-add-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp latency-monitor-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-latency-monitor-feature' = @('--active_bucket_timer_threshold', '-t', '--active_threshold_a', '-a', '--active_threshold_b', '-b', '--active_threshold_c', '-c', '--active_threshold_d', '-d', '--active_latency_config', '-f', '--active_latency_minimum_window', '-w', '--debug_log_trigger_enable', '-r', '--discard_debug_log', '-l', '--latency_monitor_feature_enable', '-e', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp internal-log' = @('--telemetry-log', '-l', '--string-log', '-s', '--output-file', '-f', '--data-area', '-a', '--telemetry-type', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp clear-fw-activate-history' = @('--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp eol-plp-failure-mode' = @('--mode', '-m', '--save', '-s', '--sel', '-S', '--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp clear-pcie-correctable-errors' = @('--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp unsupported-reqs-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp error-recovery-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp device-capability-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-dssd-power-state-feature' = @('--power-state', '-p', '--save', '-s', '--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-dssd-power-state-feature' = @('--sel', '-S', '--all', '-a', '--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-plp-health-check-interval' = @('--plp_health_interval', '-p', '--save', '-s', '--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-plp-health-check-interval' = @('--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp telemetry-string-log' = @('--output-file', '-f', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-telemetry-profile' = @('--telemetry-profile-select', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-dssd-async-event-config' = @('--enable-panic-notices', '-e', '--save', '-s', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-dssd-async-event-config' = @('--sel', '-S', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp tcg-configuration-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-error-injection' = @('--sel', '-s', '--no-uuid', '-n', '--all-ns', '-a', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-error-injection' = @('--data', '-d', '--number', '-n', '--no-uuid', '-N', '--all-ns', '-a', '--type', '-t', '--nrtdp', '-r', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-enable-ieee1667-silo' = @('--sel', '-s', '--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp set-enable-ieee1667-silo' = @('--enable', '-e', '--save', '-s', '--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp hardware-component-log' = @('--comp-id', '-i', '--list', '-l', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-latency-monitor' = @('--sel', '-s', '--namespace-id', '-n', '--no-uuid', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-clear-pcie-correctable-errors' = @('--sel', '-s', '--namespace-id', '-n', '--no-uuid', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-telemetry-profile' = @('--sel', '-s', '--namespace-id', '-n', '--no-uuid', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp persistent-event-log' = @('--action', '-a', '--log_len', '-l', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'ocp get-idle-wakeup-time' = @('--sel', '-s', '--namespace-id', '-n', '--no-uuid', '-u', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'sed discover' = @('--verbose', '-V', '--udev', '-u')
    'sed initialize' = @('--read-only', '-r')
    'sed revert' = @('--destructive', '-e', '--psid', '-p')
    'sed lock' = @('--read-only', '-r', '--ask-key', '-k')
    'sed unlock' = @('--read-only', '-r', '--ask-key', '-k')
    'sed password' = @()
    'solidigm id-ctrl' = @('--vendor-specific', '-V', '--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm smart-log-add' = @('--namespace-id', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm vs-smart-add-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm vs-internal-log' = @('--type', '-t', '--dir-name', '-d', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm garbage-collect-log' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm market-log' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm latency-tracking-log' = @('--enable', '-e', '--disable', '-d', '--read', '-r', '--write', '-w', '--type', '-t', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm parse-telemetry-log' = @('--host-generate', '-g', '--controller-init', '-c', '--data-area', '-d', '--config-file', '-j', '--source-file', '-s', '--jq-filter', '-q', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm clear-pcie-correctable-errors ' = @('--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm clear-fw-activate-history' = @('--no-uuid', '-n', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm vs-fw-activate-history' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm log-page-directory' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm temp-stats' = @('--raw-binary', '-b', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm vs-drive-info' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm cloud-SSDplugin-version' = @('--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
    'solidigm workload-tracker' = @('--uuid-index', '-U', '--enable', '-e', '--disable', '-d', '--sample-time', '-s', '--type', '-t', '--run-time', '-r', '--flush-freq', '-f', '--wall-clock', '-w', '--trigger-field', '-T', '--trigger-threshold', '-V', '--trigger-on-delta', '-D', '--trigger-on-latency', '-L', '--verbose', '-v', '--output-format', '-o', '--timeout', '--dry-run', '--no-retries', '--no-ioctl-probing', '--output-format-version')
}

Register-ArgumentCompleter -Native -CommandName nvme -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    # tokens[0] is 'nvme'. Determine command context.
    $nonOpt = @($tokens[1..($tokens.Count-1)] | Where-Object { $_ -notlike '-*' })

    # Completing the (sub)command name itself.
    if ($nonOpt.Count -le 1) {
        return $script:NvmeCommands | Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    $first = $nonOpt[0]
    $key = $null
    if ($script:NvmePluginCommands.ContainsKey($first)) {
        if ($nonOpt.Count -le 2) {
            return $script:NvmePluginCommands[$first] | Where-Object { $_ -like "$wordToComplete*" } |
                ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
        }
        $key = "$first $($nonOpt[1])"
    } else {
        $key = $first
    }

    if ($script:NvmeOptions.ContainsKey($key)) {
        return $script:NvmeOptions[$key] | Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }
    }
}
